// @vitest-environment node
/**
 * The contract chain: the server's pydantic models -> turbotab/server/openapi.json
 * (a Python test fails when that drifts from the app) -> src/api/generated.ts (this
 * test fails when that drifts from openapi.json). Fix a failure with
 *
 *   venv/bin/python -m turbotab.server.openapi --write && npm run gen:api
 */
import openapiTS, { astToString } from "openapi-typescript";
import { expect, it } from "vitest";
import openapi from "../../../server/openapi.json?raw";
import generated from "./generated.ts?raw";

const HEADER = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`;

it("src/api/generated.ts is what npm run gen:api makes of the committed openapi.json", async () => {
  const expected = HEADER + astToString(await openapiTS(openapi));
  expect(generated === expected, "generated.ts is out of date: run npm run gen:api").toBe(true);
});
