/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fs List
         * @description The entries of one folder on this machine (local mode only). Hidden entries are left out.
         */
        get: operations["fs_list_api_fs_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description Every project in the workspace, newest first.
         */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Open a file on this machine by its path (local mode only). Ingest starts as a job.
         */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Project
         * @description Upload a data file (multipart field ``file``). It is streamed to disk as it arrives.
         */
        post: operations["upload_project_api_projects_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__pid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide
         * @description Record a decision. Stages downstream of the slot it writes recompute.
         */
        post: operations["decide_api_projects__pid__decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/stages/{stage}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stage Result
         * @description A stage's artifact: the current one (``fresh``), else the newest older one, else null.
         */
        get: operations["stage_result_api_projects__pid__stages__stage__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/stages/{stage}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Stage
         * @description Compute a stage for the current answers again, after it failed or was cancelled.
         *
         *     Stages it waits on that failed or were cancelled are retried too. A stage
         *     that is fresh, in flight or blocked is left as it is. Returns its status.
         */
        post: operations["run_stage_api_projects__pid__stages__stage__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description The views that show what recording ``decision`` would change. Nothing is recorded.
         *
         *     At most three views, the first primary. Once the split exists, held-out rows are never read.
         */
        post: operations["preview_api_projects__pid__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Table
         * @description Rows ``[offset, offset + limit)`` in file order.
         */
        get: operations["table_api_projects__pid__table_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Columns */
        get: operations["columns_api_projects__pid__columns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/columns/{name}/histogram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Histogram */
        get: operations["histogram_api_projects__pid__columns__name__histogram_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/jobs/{jid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_projects__pid__jobs__jid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/jobs/{jid}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Stop a job. It is not rerun by itself; the returned view may still say running for ~1 s.
         */
        post: operations["cancel_job_api_projects__pid__jobs__jid__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{pid}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_projects__pid__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ColumnSummary */
        ColumnSummary: {
            /** Name */
            name: string;
            /**
             * Dtype
             * @enum {string}
             */
            dtype: "numeric" | "integer" | "boolean" | "categorical" | "datetime" | "text";
            /** N */
            n: number;
            /** N Missing */
            n_missing: number;
            /** N Unique */
            n_unique: number;
            /** Mean */
            mean: number | null;
            /** Std */
            std: number | null;
            /** Min */
            min: number | null;
            /** Q25 */
            q25: number | null;
            /** Median */
            median: number | null;
            /** Q75 */
            q75: number | null;
            /** Max */
            max: number | null;
            /** Top */
            top: components["schemas"]["ValueCount"][] | null;
        };
        /**
         * CreateProject
         * @description Open a file on this machine by its path (local mode only).
         */
        CreateProject: {
            /** Path */
            path: string;
        };
        /** DecisionRecord */
        DecisionRecord: {
            /** Id */
            id: string;
            /** Seq */
            seq: number;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Note */
            note: string | null;
            /** Sentence */
            sentence: string | null;
            /** Decision */
            decision: components["schemas"]["SetLens"] | components["schemas"]["SetTarget"] | components["schemas"]["SetTask"] | components["schemas"]["SetPurpose"] | components["schemas"]["Revert"] | components["schemas"]["SetRoles"] | components["schemas"]["SetEnergyAdjustment-Output"] | components["schemas"]["SetExclusions-Output"] | components["schemas"]["SetMissing"] | components["schemas"]["SetSplit-Output"] | components["schemas"]["SelectModels"] | components["schemas"]["SetSubstitution-Output"];
        };
        /** DistributionView */
        DistributionView: {
            /** Title */
            title: string;
            /** Caption */
            caption: string;
            /** Emphasis */
            emphasis: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "distribution";
            /** Column */
            column: string;
            before: components["schemas"]["HistogramData"];
            after: components["schemas"]["HistogramData"];
            /** Before Label */
            before_label: string;
            /** After Label */
            after_label: string;
            /** Cuts */
            cuts: number[];
        };
        /** EnergyAdjustment */
        EnergyAdjustment: {
            /**
             * Method
             * @enum {string}
             */
            method: "none" | "standard" | "residual" | "density_multivariate" | "density" | "partition";
            /** Energy Column */
            energy_column: string | null;
            /** Nutrients */
            nutrients: string[];
            /**
             * Log Transform
             * @default false
             */
            log_transform: boolean;
            /** Strata */
            strata: string | null;
        };
        /** ExclusionRule */
        "ExclusionRule-Input": {
            /**
             * Kind
             * @default range
             * @constant
             */
            kind: "range";
            /** Column */
            column: string;
            /** Low */
            low?: number | null;
            /** High */
            high?: number | null;
            by?: components["schemas"]["RangeByLevel"] | null;
            /** Reason */
            reason: string;
        };
        /** ExclusionRule */
        "ExclusionRule-Output": {
            /**
             * Kind
             * @default range
             * @constant
             */
            kind: "range";
            /** Column */
            column: string;
            /** Low */
            low: number | null;
            /** High */
            high: number | null;
            by: components["schemas"]["RangeByLevel"] | null;
            /** Reason */
            reason: string;
        };
        /** Exit */
        Exit: {
            /** Label */
            label: string;
            /** Decision */
            decision: (components["schemas"]["SetLens"] | components["schemas"]["SetTarget"] | components["schemas"]["SetTask"] | components["schemas"]["SetPurpose"] | components["schemas"]["Revert"] | components["schemas"]["SetRoles"] | components["schemas"]["SetEnergyAdjustment-Output"] | components["schemas"]["SetExclusions-Output"] | components["schemas"]["SetMissing"] | components["schemas"]["SetSplit-Output"] | components["schemas"]["SelectModels"] | components["schemas"]["SetSubstitution-Output"]) | null;
        };
        /** FsEntry */
        FsEntry: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Is Dir */
            is_dir: boolean;
            /** Size */
            size: number | null;
        };
        /** FsListing */
        FsListing: {
            /** Path */
            path: string;
            /** Parent */
            parent: string | null;
            /** Entries */
            entries: components["schemas"]["FsEntry"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Version */
            version: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "local" | "server";
            /** Workers */
            workers: number;
        };
        /** Histogram */
        Histogram: {
            /** Column */
            column: string;
            /** Edges */
            edges: number[];
            /** Counts */
            counts: number[];
            /** N Missing */
            n_missing: number;
        };
        /** HistogramData */
        HistogramData: {
            /** Edges */
            edges: number[];
            /** Counts */
            counts: number[];
            /**
             * N Missing
             * @default 0
             */
            n_missing: number;
        };
        /** InterviewStep */
        InterviewStep: {
            /**
             * Key
             * @enum {string}
             */
            key: "lens" | "target" | "task" | "purpose" | "roles" | "exclusions" | "missing" | "split" | "energy_adjustment" | "models" | "substitution";
            /**
             * Status
             * @enum {string}
             */
            status: "answered" | "open" | "waiting" | "skipped" | "not_applicable";
            /** Decision Id */
            decision_id: string | null;
            /** Reason */
            reason: string | null;
            /**
             * Waiting On
             * @default []
             */
            waiting_on: string[];
        };
        /** JobView */
        JobView: {
            /** Job Id */
            job_id: string;
            /** Label */
            label: string;
            /** Stage */
            stage: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "done" | "error" | "cancelled";
            /** Progress */
            progress: number | null;
            /** Message */
            message: string | null;
            /** Error */
            error: string | null;
        };
        /** Lineage */
        Lineage: {
            /** Nodes */
            nodes: components["schemas"]["LineageNode"][];
            /** Links */
            links: components["schemas"]["LineageLink"][];
            /**
             * Collapsed
             * @default false
             */
            collapsed: boolean;
        };
        /** LineageLink */
        LineageLink: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Operation */
            operation: string;
        };
        /** LineageNode */
        LineageNode: {
            /** Id */
            id: string;
            /** Column */
            column: string | null;
            /**
             * Lane
             * @enum {string}
             */
            lane: "raw" | "adjusted" | "matrix";
            /** Role */
            role: ("identifier" | "exposure" | "energy" | "covariate" | "design" | "flag" | "time" | "excluded") | null;
            /** Label */
            label: string;
            /** Formula */
            formula: string | null;
            /** Group */
            group: string | null;
            /**
             * Count
             * @default 1
             */
            count: number;
        };
        /** LineageView */
        LineageView: {
            /** Title */
            title: string;
            /** Caption */
            caption: string;
            /** Emphasis */
            emphasis: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "lineage";
            before: components["schemas"]["Lineage"] | null;
            after: components["schemas"]["Lineage"];
        };
        /** PreviewResult */
        PreviewResult: {
            /** Kind */
            kind: string;
            /** Views */
            views: (components["schemas"]["RowFlowView"] | components["schemas"]["LineageView"] | components["schemas"]["TableFocusView"] | components["schemas"]["DistributionView"] | components["schemas"]["RelationshipView"])[];
            /** Basis */
            basis: string;
            /** Note */
            note: string | null;
        };
        /**
         * ProjectState
         * @description The fold of the decision log. Later milestones add slots as fields.
         */
        ProjectState: {
            /** Lens */
            lens: ("metabolomics" | "genomics" | "dietary" | "clinical" | "survey")[] | null;
            /** Target */
            target: string | null;
            /** Task */
            task: ("regression" | "binary" | "multiclass") | null;
            /** Purpose */
            purpose: ("prediction" | "inference") | null;
            /** Roles */
            roles: {
                [key: string]: "identifier" | "exposure" | "energy" | "covariate" | "design" | "flag" | "time" | "excluded";
            } | null;
            energy_adjustment: components["schemas"]["EnergyAdjustment"] | null;
            /** Exclusions */
            exclusions: components["schemas"]["ExclusionRule-Output"][] | null;
            /** Missing */
            missing: ("complete_case" | "impute") | null;
            split: components["schemas"]["SplitSpec"] | null;
            /** Models */
            models: string[] | null;
            substitution: components["schemas"]["SubstitutionSpec"] | null;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "path" | "upload";
            /** Source Name */
            source_name: string;
            /** N Rows */
            n_rows: number | null;
            /** N Cols */
            n_cols: number | null;
            ingest: components["schemas"]["StageStatus"] | null;
        };
        /** ProjectView */
        ProjectView: {
            summary: components["schemas"]["ProjectSummary"];
            state: components["schemas"]["ProjectState"];
            /** Decisions */
            decisions: components["schemas"]["DecisionRecord"][];
            /** Stages */
            stages: {
                [key: string]: components["schemas"]["StageStatus"];
            };
            /** Interview */
            interview: components["schemas"]["InterviewStep"][];
        };
        /**
         * RangeByLevel
         * @description Different plausible ranges per level of another column (e.g. by sex).
         */
        RangeByLevel: {
            /** Column */
            column: string;
            /** Ranges */
            ranges: {
                [key: string]: [
                    number | null,
                    number | null
                ];
            };
        };
        /**
         * Refusal
         * @description Every error the API answers itself; HTTP 409 when a decision is refused.
         */
        Refusal: {
            error: components["schemas"]["RefusalDetail"];
        };
        /** RefusalDetail */
        RefusalDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Exits */
            exits: components["schemas"]["Exit"][];
        };
        /**
         * RelationshipView
         * @description A before/after scatter, e.g. a nutrient against energy before and after adjustment.
         */
        RelationshipView: {
            /** Title */
            title: string;
            /** Caption */
            caption: string;
            /** Emphasis */
            emphasis: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "relationship";
            /** X Label */
            x_label: string;
            /** Y Label Before */
            y_label_before: string;
            /** Y Label After */
            y_label_after: string;
            /** Points Before */
            points_before: [
                number,
                number
            ][];
            /** Points After */
            points_after: [
                number,
                number
            ][];
            /** R Before */
            r_before: number | null;
            /** R After */
            r_after: number | null;
        };
        /** Revert */
        Revert: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "revert";
            /** Decision Id */
            decision_id: string;
        };
        /** RowFlowView */
        RowFlowView: {
            /** Title */
            title: string;
            /** Caption */
            caption: string;
            /** Emphasis */
            emphasis: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "row_flow";
            /** Before */
            before: components["schemas"]["RowStep"][];
            /** After */
            after: components["schemas"]["RowStep"][];
        };
        /**
         * RowStep
         * @description One step of the participant flow (CONSORT/STROBE style).
         */
        RowStep: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** N */
            n: number;
            /**
             * Dropped
             * @default 0
             */
            dropped: number;
            /** Reason */
            reason: string | null;
            /** Decision Id */
            decision_id: string | null;
        };
        /** SelectModels */
        SelectModels: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "select_models";
            /** Models */
            models: string[];
        };
        /** SetEnergyAdjustment */
        "SetEnergyAdjustment-Input": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "set_energy_adjustment";
            /**
             * Method
             * @enum {string}
             */
            method: "none" | "standard" | "residual" | "density_multivariate" | "density" | "partition";
            /** Energy Column */
            energy_column?: string | null;
            /** Nutrients */
            nutrients?: string[];
            /**
             * Log Transform
             * @default false
             */
            log_transform: boolean;
            /** Strata */
            strata?: string | null;
        };
        /** SetEnergyAdjustment */
        "SetEnergyAdjustment-Output": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "set_energy_adjustment";
            /**
             * Method
             * @enum {string}
             */
            method: "none" | "standard" | "residual" | "density_multivariate" | "density" | "partition";
            /** Energy Column */
            energy_column: string | null;
            /** Nutrients */
            nutrients: string[];
            /**
             * Log Transform
             * @default false
             */
            log_transform: boolean;
            /** Strata */
            strata: string | null;
        };
        /**
         * SetExclusions
         * @description Row exclusions; an empty list is the answer "keep every row".
         */
        "SetExclusions-Input": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "set_exclusions";
            /** Rules */
            rules: components["schemas"]["ExclusionRule-Input"][];
        };
        /**
         * SetExclusions
         * @description Row exclusions; an empty list is the answer "keep every row".
         */
        "SetExclusions-Output": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "set_exclusions";
            /** Rules */
            rules: components["schemas"]["ExclusionRule-Output"][];
        };
        /** SetLens */
        SetLens: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "set_lens";
            /** Lenses */
            lenses: ("metabolomics" | "genomics" | "dietary" | "clinical" | "survey")[];
        };
        /** SetMissing */
        SetMissing: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "set_missing";
            /**
             * Strategy
             * @enum {string}
             */
            strategy: "complete_case" | "impute";
        };
        /** SetPurpose */
        SetPurpose: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "set_purpose";
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "prediction" | "inference";
        };
        /**
         * SetRoles
         * @description The confirmed reading of every column except the outcome.
         */
        SetRoles: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "set_roles";
            /** Roles */
            roles: {
                [key: string]: "identifier" | "exposure" | "energy" | "covariate" | "design" | "flag" | "time" | "excluded";
            };
        };
        /** SetSplit */
        "SetSplit-Input": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "set_split";
            /** Holdout */
            holdout: number;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Folds
             * @default 5
             */
            folds: number;
        };
        /** SetSplit */
        "SetSplit-Output": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "set_split";
            /** Holdout */
            holdout: number;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Folds
             * @default 5
             */
            folds: number;
        };
        /** SetSubstitution */
        "SetSubstitution-Input": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "set_substitution";
            /** Donor */
            donor: string;
            /** Recipient */
            recipient: string;
            /**
             * Step Kcal
             * @default 100
             */
            step_kcal: number;
        };
        /** SetSubstitution */
        "SetSubstitution-Output": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "set_substitution";
            /** Donor */
            donor: string;
            /** Recipient */
            recipient: string;
            /**
             * Step Kcal
             * @default 100
             */
            step_kcal: number;
        };
        /** SetTarget */
        SetTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "set_target";
            /** Column */
            column: string;
        };
        /**
         * SetTask
         * @description An override of task detection, for the outcome column it names.
         *
         *     It stands only while ``column`` is the target (see :func:`fold`).
         */
        SetTask: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "set_task";
            /** Column */
            column: string;
            /**
             * Task
             * @enum {string}
             */
            task: "regression" | "binary" | "multiclass";
        };
        /** SplitSpec */
        SplitSpec: {
            /** Holdout */
            holdout: number;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Folds
             * @default 5
             */
            folds: number;
        };
        /** StageResult */
        StageResult: {
            /** Stage */
            stage: string;
            /** Key */
            key: string | null;
            /** Fresh */
            fresh: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "queued" | "running" | "fresh" | "stale" | "blocked" | "error";
            /** Artifact */
            artifact: {
                [key: string]: unknown;
            } | null;
        };
        /** StageStatus */
        StageStatus: {
            /** Stage */
            stage: string;
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "queued" | "running" | "fresh" | "stale" | "blocked" | "error";
            /** Key */
            key: string | null;
            /**
             * Fresh
             * @default false
             */
            fresh: boolean;
            /**
             * Missing
             * @default []
             */
            missing: string[];
            /** Error */
            error: string | null;
            /** Job Id */
            job_id: string | null;
            /** Progress */
            progress: number | null;
            /** Updated At */
            updated_at: string | null;
            /**
             * Cancelled
             * @default false
             */
            cancelled: boolean;
        };
        /** SubstitutionSpec */
        SubstitutionSpec: {
            /** Donor */
            donor: string;
            /** Recipient */
            recipient: string;
            /**
             * Step Kcal
             * @default 100
             */
            step_kcal: number;
        };
        /**
         * TableFocusView
         * @description The working table narrowed to the columns this choice touches (≤ 12 shown, ≤ 8 rows).
         */
        TableFocusView: {
            /** Title */
            title: string;
            /** Caption */
            caption: string;
            /** Emphasis */
            emphasis: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "table_focus";
            /** Columns Before */
            columns_before: string[];
            /** Columns After */
            columns_after: string[];
            /** Rows */
            rows: components["schemas"]["TableRow"][];
            /** Changed */
            changed: [
                number,
                string
            ][];
            /** N Affected Columns */
            n_affected_columns: number;
        };
        /** TableRow */
        TableRow: {
            /** Row Id */
            row_id: number;
            /** Before */
            before: {
                [key: string]: unknown;
            };
            /** After */
            after: {
                [key: string]: unknown;
            };
        };
        /** TableWindow */
        TableWindow: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: unknown[][];
            /** Total Rows */
            total_rows: number;
            /** Offset */
            offset: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValueCount */
        ValueCount: {
            /** Value */
            value: unknown;
            /** Count */
            count: number;
        };
        /**
         * CohortArtifact
         * @description The ``cohort`` artifact (a Bundle's ``data``): the participant flow.
         */
        CohortArtifact: {
            /** Steps */
            steps: components["schemas"]["RowStep"][];
            /** N Final */
            n_final: number;
            /** Predictors */
            predictors: string[];
        };
        /** ColumnInfo */
        ColumnInfo: {
            /** Name */
            name: string;
            /**
             * Dtype
             * @enum {string}
             */
            dtype: "numeric" | "integer" | "boolean" | "categorical" | "datetime" | "text";
            /** Physical Type */
            physical_type: string;
            /** N Missing */
            n_missing: number;
            /** N Unique */
            n_unique: number;
            /** Sample */
            sample: unknown[];
        };
        /**
         * DatasetInfo
         * @description The ``ingest`` artifact.
         */
        DatasetInfo: {
            /** N Rows */
            n_rows: number;
            /** N Cols */
            n_cols: number;
            /** Columns */
            columns: components["schemas"]["ColumnInfo"][];
            /** Source Bytes */
            source_bytes: number;
            /** Parquet Bytes */
            parquet_bytes: number;
            /** Ingest Seconds */
            ingest_seconds: number;
            /** Fingerprint */
            fingerprint: string;
            /** Warnings */
            warnings: string[];
        };
        /** Finding */
        Finding: {
            /** Id */
            id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /** Why It Matters */
            why_it_matters: string | null;
            /** Affected Columns */
            affected_columns: string[];
            /**
             * Source
             * @enum {string}
             */
            source: "profile" | "pack" | "structural";
            /** Lens */
            lens: ("metabolomics" | "genomics" | "dietary" | "clinical" | "survey") | null;
            evidence: components["schemas"]["FindingEvidence"] | null;
        };
        /** FindingEvidence */
        FindingEvidence: {
            /** Status */
            status: string;
            /** Source */
            source: string;
        };
        /**
         * FindingsArtifact
         * @description The ``findings`` artifact.
         */
        FindingsArtifact: {
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Basis */
            basis: string;
        };
        /** LensHint */
        LensHint: {
            /**
             * Lens
             * @enum {string}
             */
            lens: "metabolomics" | "genomics" | "dietary" | "clinical" | "survey";
            /** Because */
            because: string;
        };
        /**
         * ProfileArtifact
         * @description The ``profile`` artifact.
         */
        ProfileArtifact: {
            /** Columns */
            columns: components["schemas"]["ColumnSummary"][];
            /** Lens Hints */
            lens_hints: components["schemas"]["LensHint"][];
            /** Basis */
            basis: string;
        };
        /** Repeats */
        Repeats: {
            /** Column */
            column: string;
            /** N Units */
            n_units: number;
            /** Max Rows Per Unit */
            max_rows_per_unit: number;
        };
        /** RoleProposal */
        RoleProposal: {
            /** Column */
            column: string;
            /**
             * Proposed
             * @enum {string}
             */
            proposed: "identifier" | "exposure" | "energy" | "covariate" | "design" | "flag" | "time" | "excluded";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Reason */
            reason: string;
            /** Linked To */
            linked_to: string | null;
            /** Unit */
            unit: string | null;
        };
        /**
         * RolesArtifact
         * @description The ``roles`` artifact: a proposed role for every column but the outcome.
         */
        RolesArtifact: {
            /** Columns */
            columns: components["schemas"]["RoleProposal"][];
            repeats: components["schemas"]["Repeats"] | null;
        };
        /**
         * SplitArtifact
         * @description The ``split`` artifact (a Bundle's ``data``): held-out rows and folds.
         */
        SplitArtifact: {
            /** N Train */
            n_train: number;
            /** N Holdout */
            n_holdout: number;
            /** Holdout */
            holdout: number;
            /** Seed */
            seed: number;
            /** Folds */
            folds: number;
            /** Grouped By */
            grouped_by: string | null;
            /** N Groups */
            n_groups: number | null;
            /** Stratified */
            stratified: boolean;
            /** Note */
            note: string;
        };
        /**
         * TargetInfo
         * @description The ``target_info`` artifact.
         */
        TargetInfo: {
            /** Column */
            column: string;
            /**
             * Task
             * @enum {string}
             */
            task: "regression" | "binary" | "multiclass";
            /**
             * Detected Task
             * @enum {string}
             */
            detected_task: "regression" | "binary" | "multiclass";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Reason */
            reason: string;
            histogram: components["schemas"]["Histogram"] | null;
            /** Classes */
            classes: components["schemas"]["ValueCount"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    fs_list_api_fs_list_get: {
        parameters: {
            query?: {
                /** @description A folder; default: your home folder */
                path?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FsListing"];
                };
            };
            /** @description Server mode, or a folder TurboTab may not read */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description No such folder */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProject"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
            /** @description Not a readable data file */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Server mode: open files by uploading them */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description No file at that path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_project_api_projects_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
            /** @description No file, or not a readable data file */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    get_project_api_projects__pid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"];
                };
            };
            /** @description No such project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_projects__pid__decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetLens"] | components["schemas"]["SetTarget"] | components["schemas"]["SetTask"] | components["schemas"]["SetPurpose"] | components["schemas"]["Revert"] | components["schemas"]["SetRoles"] | components["schemas"]["SetEnergyAdjustment-Input"] | components["schemas"]["SetExclusions-Input"] | components["schemas"]["SetMissing"] | components["schemas"]["SetSplit-Input"] | components["schemas"]["SelectModels"] | components["schemas"]["SetSubstitution-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"];
                };
            };
            /** @description No such project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description The decision was refused and not recorded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stage_result_api_projects__pid__stages__stage__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                stage: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageResult"];
                };
            };
            /** @description No such project or stage */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_stage_api_projects__pid__stages__stage__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                stage: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageStatus"];
                };
            };
            /** @description No such project or stage */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_projects__pid__preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetLens"] | components["schemas"]["SetTarget"] | components["schemas"]["SetTask"] | components["schemas"]["SetPurpose"] | components["schemas"]["Revert"] | components["schemas"]["SetRoles"] | components["schemas"]["SetEnergyAdjustment-Input"] | components["schemas"]["SetExclusions-Input"] | components["schemas"]["SetMissing"] | components["schemas"]["SetSplit-Input"] | components["schemas"]["SelectModels"] | components["schemas"]["SetSubstitution-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResult"];
                };
            };
            /** @description No such project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description The decision would be refused, or the table is not read yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    table_api_projects__pid__table_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                /** @description Comma-separated column names; default: all */
                columns?: string | null;
            };
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableWindow"];
                };
            };
            /** @description No such project or column */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description The table has not been read yet (the ingest stage is not fresh) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    columns_api_projects__pid__columns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnSummary"][];
                };
            };
            /** @description No such project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description The table has not been read yet (the ingest stage is not fresh) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    histogram_api_projects__pid__columns__name__histogram_get: {
        parameters: {
            query?: {
                bins?: number;
            };
            header?: never;
            path: {
                pid: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Histogram"];
                };
            };
            /** @description Not a numeric column */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description No such project or column */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description The table has not been read yet (the ingest stage is not fresh) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_projects__pid__jobs__jid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                jid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description No such job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_projects__pid__jobs__jid__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
                jid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description No such job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_projects__pid__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description No such project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
