"""
turbotab.archive — durability, using `utils/session_manager.py`'s schema.

**Ported, not redesigned.** `session_manager` already solves this and already
handles the hardest member: the sealed lockbox, whose labels must survive a
save/restore *verbatim* because re-drawing them with a lost non-default fraction
would silently change the test set every prior result was scored on.

The contract it encodes, which `_NEVER_PERSIST` states as a drop-list rather
than a prohibition:

> **Persist decisions and inputs; regenerate derivatives.**

Trained models, fitted pipelines, splits, metrics and profiles are dropped
because they are unsafe to pickle or cheap to rebuild — the comments in
`session_manager` say so directly: *"regenerated by re-running Page 06"*,
*"regenerated from raw_data + split_config"*. `turbotab.cascade` already knows
which keys are derivatives, so the drop-list is derived from the graph instead
of maintained by hand.

Same members, same names, same schema version, so an archive written here is
readable there and vice versa:

    manifest.json     schema_version, saved_at, saved_keys, skipped_keys, members
    config.json       target, task type, per-model pipeline SPECS, plain config
    lockbox.json      sealed labels + every disclosure the chip reports
    cohort.json       the active cohort filter, by row label
    provenance.json   the decision record
    data/*.parquet    the tables

**The guard.** :func:`assert_no_participant_data` checks the operational meaning
of "never persist participant data": no cell value from the loaded frame appears
anywhere in the serialized *project*. The frame itself travels as parquet, which
is the user saving their own session; the decision record must not become a
second, unmanaged copy of it.
"""
from __future__ import annotations

import io
import json
import zipfile
from datetime import datetime, timezone
from typing import Any, Dict, Iterable, List, Mapping, Optional, Set, Tuple

import pandas as pd

# Written by `utils/session_manager.py`. Kept identical on purpose: the two
# doors must read each other's archives, and a private schema would fork
# durability the way a private engine would fork results.
SAVE_SCHEMA_VERSION = "2.1"
ACCEPTED_SCHEMA_VERSIONS = {"2.0", "2.1"}


class ArchiveError(Exception):
    """The archive cannot be written or read honestly."""


def _looks_like_pickle(head: bytes) -> bool:
    """`session_manager` refuses pickles outright; so does this.

    A restore that executes arbitrary code is a different security posture from
    a restore that parses JSON, and the app has chosen the second.
    """
    return head[:1] in (b"\x80", b"]", b"}") and b"{" not in head[:4]


def _plain_label(x: Any) -> Any:
    """Coerce one index label exactly as `session_manager` does.

    Not cosmetic. `json.dumps(default=str)` turns a numpy int into a *string*,
    and a string label no longer matches an integer index on restore — a silent
    all-False membership test, i.e. a lockbox that quarantines nothing.
    """
    if isinstance(x, bool):
        return str(x)
    if isinstance(x, int):
        return x
    if hasattr(x, "item"):
        v = x.item()
        return v if isinstance(v, int) else str(v)
    return str(x)


def _json_safe(obj: Any) -> Any:
    try:
        json.dumps(obj)
        return obj
    except (TypeError, ValueError):
        pass
    if isinstance(obj, dict):
        return {str(k): _json_safe(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_json_safe(v) for v in obj]
    return str(obj)


# ─────────────────────────────────────────────────────────────────────────────
# The guard
# ─────────────────────────────────────────────────────────────────────────────

def _is_bare_integer(text: str) -> bool:
    return text.lstrip("-").isdigit()


# Keys whose array values are row IDENTITIES rather than data. The lockbox and
# the cohort filter both hold rows by index label, which is the whole point of
# `T0-ID-001`, so those arrays are excluded from leak-checking. Their contents
# are references to rows, not the contents of rows.
_IDENTITY_KEYS = frozenset({"labels", "order"})


def _leaves(blob: str) -> Tuple[Set[str], List[str]]:
    """Scalars in the serialized project, split into exact values and prose.

    Parsed rather than substring-searched over the raw text. Searching the raw
    JSON treats the row-label array as a haystack — with labels `0..99` present,
    every two-digit cell value "appears" in the record and the guard cries leak
    on any dataset. Comparing values to values removes that.

    Two sets, because leaks arrive two ways:

    * **exact** — a value stored as a field, e.g. a cohort's filter value;
    * **prose** — a value quoted inside a sentence, which is how engine findings
      leak (*"Found 999 (4x)"*, *"e.g. '107 kg'"*). Those need a substring
      search, but only within string leaves, never across the whole document.

    Arrays under an identity key are skipped entirely: the lockbox and cohort
    hold rows by index label, and a reference to a row is not the contents of
    one.
    """
    exact: Set[str] = set()
    prose: List[str] = []

    def walk(node: Any, under_identity: bool = False) -> None:
        if isinstance(node, dict):
            for k, v in node.items():
                walk(v, under_identity or str(k) in _IDENTITY_KEYS)
        elif isinstance(node, (list, tuple)):
            for v in node:
                walk(v, under_identity)
        elif node is not None and not isinstance(node, bool) and not under_identity:
            text = str(node).strip()
            exact.add(text)
            if isinstance(node, str) and len(text) > 12:
                prose.append(text)

    try:
        walk(json.loads(blob))
    except (ValueError, TypeError) as exc:
        raise ArchiveError(
            "The guard needs the serialized project as one JSON document; use "
            "archive.serialized_json(project)."
        ) from exc
    return exact, prose


def _frame_cell_values(df: pd.DataFrame, max_per_column: int = 400) -> Set[str]:
    """Distinct cell values, as text, for leak-checking.

    Two exclusions, both because a match would be a coincidence rather than a
    leak:

    * **Column names.** A project necessarily names its columns; "the target is
      `glucose`" is a decision, not a participant's data.
    * **Bare integers.** A record legitimately states counts — 140 rows, 100 in
      the cohort, seed 42 — and those collide with any integer-valued column.
      Excluding them costs nothing, because a single integer is not a
      participant either way; what makes an integer identifying is appearing
      *alongside* other values from the same row, which is what
      :func:`assert_no_row_is_recoverable` checks.
    """
    values: Set[str] = set()
    names = {str(c) for c in df.columns}
    for pos in range(len(df.columns)):
        col = df.iloc[:, pos]
        for v in col.dropna().unique()[:max_per_column]:
            text = str(v).strip()
            if len(text) >= 3 and text not in names and not _is_bare_integer(text):
                values.add(text)
    return values


def assert_no_row_is_recoverable(
    serialized: Mapping[str, Any] | str,
    df: pd.DataFrame,
    *,
    allow: Iterable[str] = (),
    max_rows: int = 500,
    threshold: int = 3,
) -> None:
    """No single row may be reconstructible from the serialized project.

    The backstop to :func:`assert_no_participant_data`, and the sharper
    statement of what "participant data" means. One value in isolation is a
    fact about a column — a sentinel code, a category name, a count. What makes
    data *personal* is several values from the **same row** appearing together,
    because that is a person.

    This catches leaks the literal check excludes by design, notably bare
    integers: `140` alone is a row count, but `140` next to `P0001` and `6.4` is
    a participant.
    """
    blob = serialized if isinstance(serialized, str) else json.dumps(
        serialized, default=str)
    exact, prose = _leaves(blob)
    allowed = {str(a) for a in allow}
    names = {str(c) for c in df.columns}
    for label in list(df.index)[:max_rows]:
        present = 0
        for value in df.loc[label]:
            if pd.isna(value):
                continue
            token = str(value).strip()
            # Same exclusions as the value check, for the same reasons: a bare
            # integer collides with the counts a record must state ("100 of 140
            # rows"), a column name is not data, and an explicitly allowed value
            # is one a decision legitimately quotes.
            if (len(token) < 3 or token in names or token in allowed
                    or token.lower() == "nan" or _is_bare_integer(token)):
                continue
            if token in exact or any(token in line for line in prose):
                present += 1
        if present >= threshold:
            raise ArchiveError(
                f"{present} values from row {label!r} appear together in the "
                "serialized project — that row is partially reconstructible from "
                "the record. Persist decisions and inputs; regenerate derivatives.")


def assert_no_participant_data(
    serialized: Mapping[str, Any] | str,
    df: pd.DataFrame,
    *,
    allow: Iterable[str] = (),
) -> None:
    """No cell value from `df` may appear in the serialized project.

    The operational form of "never persist participant data". The project is a
    record of *decisions*; if a decision embeds the values it was made about,
    the record becomes an uncontrolled copy of the data and travels wherever the
    record travels.

    `allow` exempts values a decision legitimately quotes — a sentinel code that
    a methods sentence has to name, for instance. Every exemption is explicit,
    so the list is arguable rather than invisible.
    """
    blob = serialized if isinstance(serialized, str) else json.dumps(
        serialized, default=str)
    exact, prose = _leaves(blob)
    allowed = {str(a) for a in allow}
    leaked = sorted(v for v in _frame_cell_values(df)
                    if v not in allowed
                    and (v in exact or any(v in line for line in prose)))
    if leaked:
        raise ArchiveError(
            f"{len(leaked)} value(s) from the table appear in the serialized "
            f"project: {leaked[:8]}. Persist decisions and inputs; regenerate "
            "derivatives. If a decision legitimately quotes one of these, pass "
            "it in `allow` so the exemption is on the record.")


# ─────────────────────────────────────────────────────────────────────────────
# Writing
# ─────────────────────────────────────────────────────────────────────────────

def build_members(project) -> Dict[str, bytes]:
    """`{filename: bytes}` for every archive member, in `session_manager` order."""
    members: Dict[str, bytes] = {}
    saved: List[str] = []
    skipped: List[str] = []

    # --- the table --------------------------------------------------------
    if project.df is not None and len(project.df) > 0:
        buf = io.BytesIO()
        # index=True, unlike session_manager: row identity is the index label
        # (T0-ID-001), so dropping the index would throw away the thing the
        # lockbox and every recorded decision refer to.
        project.df.to_parquet(buf, index=True)
        members["data/working_table.parquet"] = buf.getvalue()
        saved.append("working_table")

    # --- config -----------------------------------------------------------
    config = {
        "project_id": project.id,
        "name": project.name,
        "created_at": project.created_at,
        "target_col": project.target,
        "task_type": project.task_type,
        "task_confidence": project.task_confidence,
        "task_overridden": bool(project.task_overridden),
        "row_identity": "index_labels",
        "workflow_mode": project.workflow_mode,
        # SPECS, never fitted objects. TRANSITION_PLAN §02.1: storing the fitted
        # pipeline let two models alias one instance, because the global slot
        # handed back the same object and page 06 fitted it in place.
        "pipeline_specs": {k: _json_safe(v)
                           for k, v in project.pipeline_specs.items()},
        # The Features step's decisions. Engineered columns are IN the parquet
        # already; what would be lost without these is the RECORD of how they
        # got there, and the deferred specs — which have no other home, because
        # nothing has executed them yet.
        "engineered": _json_safe(project.engineered),
        "deferred_transforms": _json_safe(project.deferred_transforms),
        "selection_spec": _json_safe(project.selection_spec) if project.selection_spec else None,
        "features_settled": bool(project.features_settled),
        "stale_downstream": _json_safe(project.stale_downstream),
        # The lens travels for the same reason the grain does, and for one more:
        # the structural diagnosis is READ under it, so a restored project that
        # lost the lens would recompute its findings under a different reading
        # of what the table is — and would do so silently, because the findings
        # are a regenerated derivative and would come back looking fresh.
        # `[]` and `None` are different answers here: `None` is never asked.
        "lens": list(project.lens) if project.lens is not None else None,
        # The orientation answer travels, and it is the sharpest case in this
        # config after `aggregation`: answering *features in rows* TRANSPOSED
        # the frame, and the parquet beside this holds the turned-around table.
        # A restored project that lost the record would hold sample-rows with
        # nothing saying they were ever columns — the receipt for an
        # irreversible operation, missing.
        "orientation": _json_safe(project.orientation) if project.orientation else None,
        # The purpose travels because the DEFAULTS downstream are read from it.
        # A restored project that lost it would silently revert to the app's old
        # assumption — prediction — and change what a dozen later questions
        # default to, with nothing saying so.
        "purpose": _json_safe(project.purpose) if project.purpose else None,
        # Questions 4 to 7. `aggregation` is the sharpest of the four: it is the
        # only one that CHANGED THE TABLE, and the parquet that travels beside
        # this config holds the combined rows. A restored project that lost the
        # record would hold a frame of person-rows with nothing saying they were
        # ever anything else — the receipt for an irreversible operation,
        # missing.
        "repeat_kind": _json_safe(project.repeat_kind) if project.repeat_kind else None,
        "unit_of_analysis": project.unit_of_analysis or None,
        "aggregation": _json_safe(project.aggregation) if project.aggregation else None,
        "temporal_prediction": (_json_safe(project.temporal_prediction)
                                if project.temporal_prediction else None),
        # The grain answer travels with the project, not just with the seal.
        # A restored project that has been sealed must not be able to answer
        # the question again, and one that has NOT been sealed must not be
        # asked twice — both need the answer itself, not only its consequence.
        "grain": _json_safe(project.grain) if project.grain else None,
        # The eligibility answer travels too, and for a sharper reason than
        # most: a restored project that lost it would ask the question again
        # AFTER its seal exists, which `set_eligibility` refuses — so the
        # project would be stuck with no way to say the step had happened.
        "eligibility": _json_safe(project.eligibility) if project.eligibility else None,
        # §05 spans two steps, so the obligation has to survive the gap
        # between them — including a save and a restore, which is the
        # longest form that gap takes.
        "obligations": _json_safe(project.obligations),
        # The Preprocess step is almost entirely DECLARATIONS, so the
        # archive is the only place they live: nothing has executed them,
        # and a restored project that lost them would have no record that
        # the step happened at all.
        "selected_models": [str(m) for m in project.selected_models],
        "preparation_mode": project.preparation_mode,
        "model_recipes": _json_safe(project.model_recipes),
        "missingness": _json_safe(project.missingness),
        "preprocess_settled": bool(project.preprocess_settled),
    }
    members["config.json"] = json.dumps(config, indent=2, default=str).encode("utf-8")
    saved.append("config")

    # --- lockbox (schema 2.1) --------------------------------------------
    if project.lockbox and project.lockbox.get("labels") is not None:
        lb = project.lockbox
        members["lockbox.json"] = json.dumps({
            "labels": [_plain_label(l) for l in lb["labels"]],
            "fraction": float(lb.get("fraction", 0.15)),
            "seed": int(lb.get("seed", 42)),
            "n_total": int(lb.get("n_total", 0)),
            "n_test": int(lb.get("n_test", len(lb["labels"]))),
            "signature": str(lb.get("signature", "")),
            "stratified": bool(lb.get("stratified", False)),
            "fraction_requested": float(lb.get("fraction_requested",
                                               lb.get("fraction", 0.15))),
            "target_col": str(lb.get("target_col") or ""),
            "strata": [str(c) for c in (lb.get("strata") or [])],
            "strata_requested": [str(c) for c in (lb.get("strata_requested") or [])],
            "group_col": str(lb["group_col"]) if lb.get("group_col") else None,
            "group_kind": str(lb["group_kind"]) if lb.get("group_kind") else None,
            "group_noun": str(lb["group_noun"]) if lb.get("group_noun") else None,
            "n_test_groups": (int(lb["n_test_groups"])
                              if lb.get("n_test_groups") is not None else None),
            # Constitution §03: the seal states its own basis. This member is
            # an explicit whitelist, so a basis added to the lockbox and not
            # added here is dropped on save — the seal would come back from
            # the archive unable to say what it rests on, which is precisely
            # the `group_col: None` ambiguity §03 exists to remove.
            "seal_basis": str(lb["seal_basis"]) if lb.get("seal_basis") else None,
            "basis_source": (str(lb["basis_source"])
                             if lb.get("basis_source") else None),
            "n_groups": (int(lb["n_groups"])
                         if lb.get("n_groups") is not None else None),
            "exploratory": bool(lb.get("exploratory", False)),
        }, indent=2).encode("utf-8")
        saved.append("test_lockbox")

    # --- the active cohort filter (schema 2.1) ---------------------------
    # ARCHITECTURE.md §02: a project that models "the working table" without
    # modeling "the active cohort filter" silently deletes the newest feature.
    if project.cohort and project.cohort.get("labels"):
        run = project.cohort
        members["cohort.json"] = json.dumps({
            "column": str(run["column"]),
            "value": _plain_label(run.get("value")),
            "label": str(run.get("label", "")),
            "labels": [_plain_label(x) for x in run["labels"]],
            "n_rows": int(run.get("n_rows", len(run["labels"]))),
            "n_total": int(run.get("n_total", 0)),
            "position": int(run.get("position", 1)),
            "of": int(run.get("of", 1)),
            "order": [str(x) for x in (run.get("order") or [])],
            "target_col": str(run.get("target_col") or ""),
            "dropped_features": [str(x) for x in (run.get("dropped_features") or [])],
        }, indent=2).encode("utf-8")
        saved.append("cohort_run")

    # --- the record -------------------------------------------------------
    members["provenance.json"] = json.dumps(
        [d.to_dict() for d in project.decisions], indent=2, default=str
    ).encode("utf-8")
    saved.append("decisions")

    # Derivatives are not written. The graph decides which those are, so a new
    # result key is dropped automatically instead of being remembered.
    from turbotab import cascade
    skipped.extend(sorted(cascade.all_result_keys()))

    members["manifest.json"] = json.dumps({
        "schema_version": SAVE_SCHEMA_VERSION,
        "saved_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "workflow_step": project.readiness().next_step().key
                         if project.readiness().next_step() else "complete",
        "saved_keys": sorted(set(saved)),
        "skipped_keys": sorted(set(skipped)),
        "members": sorted(members.keys()) + ["manifest.json"],
    }, indent=2).encode("utf-8")
    return members


def to_bytes(project) -> bytes:
    """Pack the project into a zip, manifest first so readers can stream it."""
    members = build_members(project)
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("manifest.json", members.pop("manifest.json"))
        for name in sorted(members):
            zf.writestr(name, members[name])
    return buf.getvalue()


def serialized_json(project) -> str:
    """Every JSON member, as one document — what the guards inspect.

    One document rather than a concatenation, so the guards can parse it and
    compare values to values instead of searching raw text. The parquet member
    is excluded by construction: that is the table itself, travelling as the
    table, which is the user saving their own data.
    """
    members = build_members(project)
    return json.dumps({name: json.loads(raw.decode("utf-8"))
                       for name, raw in sorted(members.items())
                       if name.endswith(".json")}, indent=2)


# ─────────────────────────────────────────────────────────────────────────────
# Reading
# ─────────────────────────────────────────────────────────────────────────────

def from_bytes(raw: bytes):
    """Rebuild a project. Derivatives are recomputed, never read."""
    from turbotab.project import AnalysisProject

    if _looks_like_pickle(raw[:8]):
        raise ArchiveError("This file looks like a pickle. Archives are JSON and "
                           "parquet; a restore never executes code.")
    try:
        zf = zipfile.ZipFile(io.BytesIO(raw))
    except zipfile.BadZipFile as exc:
        raise ArchiveError("Not a readable archive.") from exc

    names = set(zf.namelist())
    if "manifest.json" not in names:
        raise ArchiveError("Archive has no manifest.")
    manifest = json.loads(zf.read("manifest.json"))
    version = str(manifest.get("schema_version", ""))
    if version not in ACCEPTED_SCHEMA_VERSIONS:
        raise ArchiveError(
            f"Archive schema {version!r} is not readable "
            f"(this writes {SAVE_SCHEMA_VERSION!r}, accepts "
            f"{sorted(ACCEPTED_SCHEMA_VERSIONS)}).")

    if "data/working_table.parquet" not in names:
        raise ArchiveError("Archive carries no table.")
    df = pd.read_parquet(io.BytesIO(zf.read("data/working_table.parquet")))

    config = json.loads(zf.read("config.json")) if "config.json" in names else {}
    project = AnalysisProject.from_dataframe(df, config.get("name") or "restored")
    project.id = config.get("project_id", project.id)
    project.created_at = config.get("created_at", project.created_at)
    project.target = config.get("target_col")
    project.task_type = config.get("task_type")
    project.task_confidence = config.get("task_confidence")
    project.task_overridden = bool(config.get("task_overridden", False))
    project.workflow_mode = config.get("workflow_mode", "quick")
    project.pipeline_specs = dict(config.get("pipeline_specs") or {})
    # `or None` would collapse a recorded empty list into "never asked", which
    # `normalize` already refuses to produce — but the archive must not be the
    # one place that can reintroduce the state.
    lens = config.get("lens")
    project.lens = list(lens) if isinstance(lens, list) else None
    project.orientation = config.get("orientation") or None
    project.purpose = config.get("purpose") or None
    project.repeat_kind = config.get("repeat_kind") or None
    project.unit_of_analysis = config.get("unit_of_analysis") or None
    project.aggregation = config.get("aggregation") or None
    project.temporal_prediction = config.get("temporal_prediction") or None
    project.grain = config.get("grain") or None
    project.eligibility = config.get("eligibility") or None
    project.obligations = list(config.get("obligations") or [])
    project.selected_models = list(config.get("selected_models") or [])
    project.preparation_mode = config.get("preparation_mode") or None
    project.model_recipes = dict(config.get("model_recipes") or {})
    project.missingness = list(config.get("missingness") or [])
    project.preprocess_settled = bool(config.get("preprocess_settled", False))
    project.engineered = list(config.get("engineered") or [])
    project.deferred_transforms = list(config.get("deferred_transforms") or [])
    project.selection_spec = config.get("selection_spec") or None
    project.features_settled = bool(config.get("features_settled", False))
    project.stale_downstream = list(config.get("stale_downstream") or [])

    if "lockbox.json" in names:
        project.lockbox = json.loads(zf.read("lockbox.json"))
    if "cohort.json" in names:
        project.cohort = json.loads(zf.read("cohort.json"))

    if "provenance.json" in names:
        from turbotab.project import Decision
        project.decisions = [
            Decision(id=d["id"], kind=d["kind"], subject=d.get("subject", ""),
                     text=d.get("text", ""), at=d.get("at", ""),
                     payload=d.get("payload") or {})
            for d in json.loads(zf.read("provenance.json"))
        ]

    # Derivatives were never written; they are stale by definition until
    # recomputed, and saying so is the honest state to restore into.
    project.findings, project.profile = [], None
    project.findings_stale = True
    return project
