"""
turbotab.project — the minimal `AnalysisProject`.

This is the container `st.session_state` is standing in for today: what is
currently true about one analysis. It holds a dataframe handle, the target, an
append-only list of decisions, and the findings last computed. It computes
nothing — `turbotab.engine` does that — so this module imports neither the
engine nor pandas' analysis surface, and can be reasoned about on its own.

Three commitments carried over from the transition documents:

**Row identity is index labels, never positions** (`TRANSITION_PLAN.md` §02.2).
The lockbox already stores labels; the split block stores positions; page 07
reads the second against a re-fetched frame. They agree only while the index is
a pristine `RangeIndex`, which cohort filtering, row-dropping repairs and joins
all break. This project picks labels and says so in one place —
:meth:`AnalysisProject.rows`, which uses ``.loc`` and refuses ``.iloc``.

**Decisions are append-only** (`ARCHITECTURE.md` §03). The record is what
happened; the project is what is currently true. Changing the target does not
edit the earlier decision, it appends a new one — otherwise "the target was
chosen before exploration" stops being a statement anyone can check.

**Persist decisions and inputs; regenerate derivatives.** An earlier version of
this docstring read ``_NEVER_PERSIST`` as a prohibition on writing anything to
disk. It is a **drop-list**: `utils/session_manager.py` already saves a session
as a zip of JSON and parquet — config, the ledger, provenance, the sealed
lockbox, cohort runs — and drops trained models, fitted pipelines, splits,
metrics and profiles because they are unsafe to pickle or cheap to rebuild
(*"regenerated by re-running Page 06"*). Durability is `turbotab.archive`, which
ports that schema rather than inventing one. What must never be persisted is
**participant data inside the decision record**, and
:func:`turbotab.archive.assert_no_participant_data` is the check that makes that
rule testable rather than remembered.

**The identity barrier** (`T0-ID-001`). Rows acquire identities when the lockbox
is sealed. Repairs that change what a row *is* — ``promote_header``,
``melt_repeated`` — may only run before that; repairs that merely remove rows
preserve the survivors' labels and may run either side. The project owns the
lockbox, so the project is the thing that can refuse: see
:meth:`AnalysisProject.check_repair_allowed`.
"""
from __future__ import annotations

import hashlib
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Sequence, Tuple

import pandas as pd

# Repairs that rebuild what a row IS, rather than removing rows. After the
# barrier these cannot preserve identity even in principle: `promote_header`
# re-reads the frame from a different starting row, and `melt_repeated` turns
# one row into several. The other renumbering kinds (`drop_empty_rows`,
# `drop_rows`) keep the surviving rows' labels and are allowed on either side.
PRE_BARRIER_ONLY_FIXES = frozenset({"promote_header", "melt_repeated"})


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _label(value: Any) -> Any:
    """Coerce one index label to something JSON can carry.

    Labels are scalars — ints, strings, occasionally timestamps. Anything with
    an `item()` is a numpy scalar hiding as a Python one.
    """
    if isinstance(value, (str, bool)) or value is None:
        return value
    if hasattr(value, "isoformat"):
        return value.isoformat()
    if hasattr(value, "item"):
        try:
            return value.item()
        except (ValueError, AttributeError):
            return str(value)
    if isinstance(value, (int, float)):
        return value
    return str(value)


@dataclass(frozen=True)
class _TargetView:
    """Just enough of `DataConfig` for the shared readiness predicate.

    `_data_configured` asks for `.target_col`; giving it a real DataConfig would
    make this module import the Streamlit host's state layer.
    """
    target_col: Optional[str] = None


class ProjectError(Exception):
    """The project was asked for something it cannot honestly provide."""


class GrainContradiction(ProjectError):
    """The stated grain and the data's shape disagree — one of them is wrong.

    A subclass rather than a flag, so a caller that wants to surface the
    interruption can catch it specifically while a caller that does not still
    fails loudly. `detail` carries the evidence: the columns, their distinct
    counts and how many rows each value holds, so the interruption can show
    what it saw rather than assert that it saw something.
    """

    def __init__(self, message: str, detail: Optional[Dict[str, Any]] = None):
        super().__init__(message)
        self.detail = detail or {}


@dataclass
class Decision:
    """One recorded answer. Append-only: never edited, never deleted.

    `kind` is the vocabulary the frontend and the record share:
      ``set_target`` · ``apply`` · ``defer`` · ``dismiss`` · ``flag`` · ``note``
    """
    id: str
    kind: str
    subject: str            # a finding id, a column name, or "" for a bare note
    text: str               # the sentence that goes in the transcript
    at: str
    payload: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id, "kind": self.kind, "subject": self.subject,
            "text": self.text, "at": self.at, "payload": self.payload,
        }


@dataclass
class AnalysisProject:
    """One analysis. Serializable apart from the frame it points at."""

    id: str
    name: str
    created_at: str
    df: pd.DataFrame                       # the handle — never serialized
    target: Optional[str] = None
    task_type: Optional[str] = None
    task_confidence: Optional[str] = None
    task_reasons: List[str] = field(default_factory=list)
    decisions: List[Decision] = field(default_factory=list)
    findings: List[Dict[str, Any]] = field(default_factory=list)
    profile: Optional[Dict[str, Any]] = None
    # Set when an answer changes underneath findings that were computed from the
    # old one. The findings are *marked*, never dropped: "the past is editable,
    # never silently destroyed" (PRODUCT_VISION.md §07.4).
    findings_stale: bool = False
    # True when the user contradicted the detection rather than confirming it.
    task_overridden: bool = False
    # The answer to "can one person appear in more than one row?", recorded
    # ONCE and read by both consumers (constitution §02, ASSEMBLY_SPEC §05).
    # `None` means not yet asked, and the seal cannot be drawn on `None` — that
    # is the ordering clause §01 fixes, expressed as a precondition rather than
    # as a comment somebody has to remember.
    grain: Optional[Dict[str, Any]] = None
    # Engineered columns and their receipts, in creation order. Row-local
    # transforms only: a stateful one never reaches the working table
    # (constitution §06), so it lives in `deferred_transforms` instead.
    engineered: List[Dict[str, Any]] = field(default_factory=list)
    # Stateful transforms and the selection spec, RECORDED and not executed.
    # These are what a per-model pipeline consumes; nothing here has touched a
    # value. Keeping them beside `engineered` rather than inside it is the
    # clause's own distinction made structural.
    deferred_transforms: List[Dict[str, Any]] = field(default_factory=list)
    selection_spec: Optional[Dict[str, Any]] = None
    # True once the user has answered the Features step, including by skipping
    # it. A skip must be RECORDED: a silent skip is indistinguishable from a
    # step nobody reached.
    features_settled: bool = False
    # What became stale, and WHY, most recent last. Distinct from
    # `findings_stale`, which recompute clears because findings genuinely are
    # recomputed. Models, metrics and any fitted pipeline are NOT recomputed by
    # a re-diagnosis, so a boolean that clears would say the cascade had been
    # dealt with when nothing had. DESIGN_LANGUAGE §10 wants the cascade
    # VISIBLE, so this names its cause rather than raising a flag: "age_x_bmi
    # was added" is actionable, "something changed" is not.
    stale_downstream: List[Dict[str, Any]] = field(default_factory=list)
    # The sealed holdout, in `session_manager`'s schema. Its presence is what
    # raises the identity barrier: before it exists rows are anonymous
    # positions, after it they are named.
    lockbox: Optional[Dict[str, Any]] = None
    # The active cohort filter, first-class. ARCHITECTURE.md §02: a project that
    # models "the working table" without modeling this silently deletes the
    # newest feature, and every number below it is quietly about a subset.
    cohort: Optional[Dict[str, Any]] = None
    # Per-model preprocessing SPECS — serializable, diffable, hashable — never
    # fitted objects. TRANSITION_PLAN §02.1: the global slot handed two models
    # the same live pipeline instance and page 06 fitted it in place, so their
    # fitted pipelines aliased. There is no global slot here; resolution is
    # total, and a model with no explicit spec gets one derived from its
    # registry capabilities rather than borrowing a neighbour's.
    pipeline_specs: Dict[str, Dict[str, Any]] = field(default_factory=dict)
    workflow_mode: str = "quick"
    # (finding_id, frame) for each applied fix, most recent last. Holds whole
    # frames, so it is memory the skeleton spends to keep fixes reversible.
    _history: List[Tuple[str, pd.DataFrame]] = field(default_factory=list, repr=False)

    # ── construction ────────────────────────────────────────────────────────

    @classmethod
    def from_dataframe(cls, df: pd.DataFrame, name: str) -> "AnalysisProject":
        if df is None or df.empty:
            raise ProjectError(f"'{name}' has no rows to analyze.")
        # Duplicate index labels would make row identity ambiguous — the exact
        # failure this project model exists to prevent. Catch it at the door
        # rather than at the first `.loc`.
        if df.index.has_duplicates:
            raise ProjectError(
                f"'{name}' has repeated row labels "
                f"({df.index.duplicated().sum()} of {len(df)}). Row identity in this "
                "project is the index label, so repeated labels leave no way to say "
                "which row a decision refers to."
            )
        return cls(id=uuid.uuid4().hex[:12], name=name, created_at=_now(), df=df)

    # ── row identity: labels, not positions ─────────────────────────────────

    @property
    def row_labels(self) -> List[Any]:
        """The row identities of this project, in frame order.

        These are index *labels*. A consumer that stores positions instead —
        `np.where(mask)[0]` — is storing something that stops meaning the same
        row the moment a filter or a repair changes the frame.
        """
        return [_label(v) for v in self.df.index]

    def rows(self, labels: List[Any]) -> pd.DataFrame:
        """Fetch rows by label. The one supported way to name a subset.

        Uses ``.loc``. Never ``.iloc`` — that is the convention clash in
        `TRANSITION_PLAN.md` §02.2, and it stays fixed here by not being
        available.
        """
        missing = [l for l in labels if l not in self.df.index]
        if missing:
            raise ProjectError(
                f"{len(missing)} row label(s) are not in this table: {missing[:5]}. "
                "Labels are identities — a missing one means the frame changed "
                "underneath, not that the caller should fall back to a position."
            )
        return self.df.loc[labels]

    # ── columns ─────────────────────────────────────────────────────────────

    @property
    def columns(self) -> List[Dict[str, Any]]:
        """Columns by position, with their labels.

        Positional, because `_each_column()` in the engine is positional for a
        reason: with duplicate labels `df[col]` returns a frame, not a series
        (ARCHITECTURE.md §02). `duplicated` is surfaced so the UI can decline to
        offer an ambiguous column as a target.
        """
        labels = list(self.df.columns)
        seen: Dict[Any, int] = {}
        for l in labels:
            seen[l] = seen.get(l, 0) + 1
        out = []
        for pos in range(len(labels)):
            series = self.df.iloc[:, pos]
            out.append({
                "position": pos,
                "name": str(labels[pos]),
                "dtype": str(series.dtype),
                "duplicated": seen[labels[pos]] > 1,
                "n_missing": int(series.isna().sum()),
                "n_unique": int(series.nunique(dropna=True)),
            })
        return out

    # ── state transitions ───────────────────────────────────────────────────

    def record(self, kind: str, text: str, subject: str = "",
               payload: Optional[Dict[str, Any]] = None) -> Decision:
        """Append one decision. The only way the record grows."""
        d = Decision(id=uuid.uuid4().hex[:10], kind=kind, subject=subject,
                     text=text, at=_now(), payload=payload or {})
        self.decisions.append(d)
        return d

    def set_target(self, column: str, task_type: Optional[str],
                   confidence: Optional[str], reasons: List[str]) -> Decision:
        """Choose the target and record having chosen it.

        Marks existing findings stale rather than clearing them: they were
        computed against a different question and are no longer current, but
        throwing them away would delete work the user can still see and reason
        about.
        """
        if column not in list(self.df.columns):
            raise ProjectError(f"No column named '{column}' in this table.")
        changed = self.target is not None and self.target != column
        self.target = column
        self.task_type = task_type
        self.task_confidence = confidence
        self.task_reasons = list(reasons or [])
        self.task_overridden = False
        if changed:
            self.findings_stale = True
        return self.record(
            kind="set_target", subject=column,
            text=f"{column} was chosen as the target; the task was detected as "
                 f"{task_type} at {confidence} confidence.",
            payload={"task_type": task_type, "confidence": confidence,
                     "reasons": self.task_reasons, "replaced": changed},
        )

    def override_task_type(self, task_type: str) -> Decision:
        """Let the user disagree with the detection, and record that they did.

        Required, not optional. `ml/triage.py` returns `low` confidence for a
        low-cardinality integer target and says so in its own words — *"counts
        or ordinal scores should be treated as regression. Verify or override
        below."* An interface that reports that verdict and offers no way to
        contradict it has made the choice itself, at a confidence tier the
        governing rule reserves for the user (`PRODUCT_VISION.md` §07.1).
        Classic has this control; Guided has to as well.

        The detected value is kept alongside the override, because the record
        has to be able to say what the app thought *and* what the user decided.
        """
        if task_type not in ("classification", "regression"):
            raise ProjectError(
                f"'{task_type}' is not a task type. Expected classification or regression.")
        if not self.target:
            raise ProjectError("Choose a target before setting its task type.")
        detected = self.task_type
        self.task_type = task_type
        self.task_overridden = task_type != detected
        if self.task_overridden:
            self.findings_stale = True
        return self.record(
            kind="set_task_type", subject=self.target,
            text=(f"{self.target} was treated as {task_type}, overriding the detected "
                  f"{detected} ({self.task_confidence} confidence)."
                  if self.task_overridden else
                  f"The detected task type for {self.target}, {task_type}, was confirmed."),
            payload={"task_type": task_type, "detected": detected,
                     "overridden": self.task_overridden},
        )

    # ── the identity barrier · T0-ID-001 ────────────────────────────────────

    @property
    def barrier_raised(self) -> bool:
        """True once rows have identities — i.e. once the lockbox is sealed."""
        return bool(self.lockbox and self.lockbox.get("labels"))

    def check_repair_allowed(self, fix_kind: str) -> None:
        """Refuse a pre-barrier repair once the lockbox is sealed.

        The phase rule, enforced at the one place that can enforce it. A sealed
        lockbox holds row **labels**; `promote_header` and `melt_repeated`
        rebuild the index outright, so afterwards those labels name different
        rows — or no rows. Nothing downstream can detect that, because the
        lockbox still looks perfectly well-formed. The quarantine would simply
        stop quarantining, silently, and every number scored against it would
        be describing a test set that no longer exists.

        `drop_empty_rows` and `drop_rows` also reset the index in the engine,
        but they only *remove* rows: the survivors keep their identities, and
        `turbotab.engine.preview_fix` already reports by content whether a given
        drop actually renumbered anything. Those stay allowed on either side.
        """
        if fix_kind in PRE_BARRIER_ONLY_FIXES and self.barrier_raised:
            raise ProjectError(
                f"'{fix_kind}' rebuilds what a row is, and this project has a sealed "
                f"test set of {len(self.lockbox['labels'])} rows held by label. "
                "Running it now would leave those labels naming different rows, with "
                "nothing to detect it. Structural repairs of this kind belong before "
                "the test set is sealed.")

    # ── the Features step (constitution §06) ────────────────────────────────

    def add_feature(self, key: str, columns: Sequence[str],
                    params: Optional[Dict[str, Any]] = None) -> Decision:
        """Execute a ROW-LOCAL transform and post its receipt.

        Refuses a stateful one — `features.apply` raises, and that refusal is
        the clause made executable rather than a convention.
        """
        from turbotab import features as _feat
        try:
            result = _feat.apply(self.df, key, list(columns), params)
        except _feat.FeatureRefusal as exc:
            raise ProjectError(str(exc)) from exc

        receipt = result["receipt"]
        self._history.append((f"feature::{receipt['column']}", self.df))
        self.df = result["frame"]
        self.engineered.append(receipt)
        # A new column changes the modeling problem, so everything computed
        # under the old one is stale. Marked, never dropped.
        self.findings_stale = True
        self._mark_stale(f"the column `{receipt['column']}` was added")
        return self.record(
            kind="add_feature", subject=receipt["column"],
            text=receipt["sentence"], payload=dict(receipt))

    def remove_feature(self, column: str) -> Decision:
        """Drop an engineered column. Reversibility, per feat-remove-one."""
        known = [e for e in self.engineered if e["column"] == column]
        if not known:
            raise ProjectError(
                f"'{column}' was not created here, so removing it is not this "
                f"step's to do. Only engineered columns can be removed.")
        self._history.append((f"feature::-{column}", self.df))
        self.df = self.df.drop(columns=[column])
        self.engineered = [e for e in self.engineered if e["column"] != column]
        self.findings_stale = True
        self._mark_stale(f"the column `{column}` was removed")
        return self.record(
            kind="remove_feature", subject=column,
            text=f"The engineered column `{column}` was removed.",
            payload={"column": column})

    def defer_feature(self, key: str, columns: Sequence[str],
                      params: Optional[Dict[str, Any]] = None) -> Decision:
        """Record a STATEFUL transform as a decision. Executes nothing."""
        from turbotab import features as _feat
        try:
            spec = _feat.declare(key, list(columns), params)
        except _feat.FeatureRefusal as exc:
            raise ProjectError(str(exc)) from exc
        self.deferred_transforms.append(spec)
        return self.record(
            kind="defer_feature", subject=",".join(str(c) for c in columns),
            text=spec["sentence"], payload=dict(spec))

    def set_selection(self, spec: Optional[Dict[str, Any]]) -> Decision:
        """Record what will be selected, inside the training folds.

        `spec` comes from `selection.declare`, which never selects. A spec
        carrying a `selected` list would be a selection that already ran.
        """
        if spec is not None and spec.get("selected") is not None:
            raise ProjectError(
                "This selection spec carries an already-chosen feature set. "
                "Selection is performed inside the training folds at modeling "
                "time; a set chosen now would have been chosen using the "
                "held-out rows.")
        self.selection_spec = spec
        self.findings_stale = True
        self._mark_stale(
            f"feature selection was set to {spec['label']}" if spec
            else "feature selection was cleared: every column goes to the models")
        return self.record(
            kind="set_selection", subject=(spec or {}).get("method", ""),
            text=(spec["sentence"] if spec else
                  "No feature selection: every candidate column is offered to "
                  "the models."),
            payload=dict(spec) if spec else {})

    def settle_features(self, skipped: bool = False) -> Decision:
        """End the step, including by skipping it — recorded either way."""
        self.features_settled = True
        n = len(self.engineered)
        d = len(self.deferred_transforms)
        return self.record(
            kind="settle_features", subject="",
            text=("Feature work was skipped; the original columns go forward "
                  "unchanged." if skipped else
                  f"Feature work settled: {n} column(s) added now, {d} "
                  f"transform(s) recorded for fitting inside the training "
                  f"folds"
                  + (", and a selection spec recorded."
                     if self.selection_spec else ".")),
            payload={"skipped": bool(skipped), "n_engineered": n,
                     "n_deferred": d,
                     "has_selection": self.selection_spec is not None})

    def _mark_stale(self, why: str) -> None:
        """Record that downstream results no longer describe this feature set.

        Appends rather than sets, and never clears here: nothing in this module
        recomputes a model, so clearing would be this project asserting that
        the cascade had been dealt with. The step that trains is what clears it.
        """
        self.stale_downstream.append({"why": why, "at": _now()})

    def set_grain(self, answer: str, group_col: Optional[str] = None,
                  inherited: bool = False,
                  acknowledged_contradiction: bool = False) -> Decision:
        """Record the answer to the grain question. Asked, never inferred.

        The heuristics do not reach this method. They produce a suggestion the
        user may accept and a contradiction the user must look at; what lands
        here is what the user said. `IMPORT-020` and `IMPORT-022` are both the
        engine having guessed instead.
        """
        from turbotab import grain as _grain

        if answer not in _grain.ANSWERS:
            raise ProjectError(
                f"{answer!r} is not one of {list(_grain.ANSWERS)}.")
        if self.barrier_raised:
            raise ProjectError(
                "The test set is already sealed, and it was drawn against the "
                "grain answer recorded at the time. Changing that answer now "
                "would describe a split that was not drawn this way.")
        if answer == _grain.PEOPLE_REPEAT and group_col:
            if group_col not in list(self.df.columns):
                raise ProjectError(f"No column named '{group_col}' in this table.")

        clash = _grain.contradiction(self.df, answer, group_col)
        if clash and not acknowledged_contradiction:
            # Escalate on evidence of error, never on the magnitude of a
            # consequence. Raised rather than warned because one of the two
            # readings is wrong and the caller has to say which.
            raise GrainContradiction(clash["message"], detail=clash)

        n_groups = None
        if group_col and group_col in self.df.columns:
            n_groups = int(self.df[group_col].nunique(dropna=True))
        self.grain = {
            "answer": answer,
            "group_col": group_col if answer == _grain.PEOPLE_REPEAT else None,
            "n_groups": n_groups if answer == _grain.PEOPLE_REPEAT else None,
            "basis": _grain.seal_basis(answer, group_col, n_groups),
            "basis_source": _grain.basis_source(inherited),
            "contradiction_acknowledged": bool(clash and acknowledged_contradiction),
            "contradiction": clash if clash else None,
        }
        said = {_grain.ONE_ROW_PER_PERSON: "one row per person",
                _grain.PEOPLE_REPEAT: f"people repeat, identified by '{group_col}'",
                _grain.NOT_SURE: "unknown — the shape could not be stated"}[answer]
        return self.record(
            kind="set_grain", subject=group_col or "",
            text=(f"Asked whether one person can appear in more than one row; "
                  f"the answer recorded was: {said}."),
            payload=dict(self.grain))

    def seal_lockbox(self, labels: Sequence[Any], **disclosure: Any) -> Decision:
        """Raise the barrier: freeze the holdout and record having done so.

        Sealed once. A second seal is refused rather than silently redrawn,
        because a redraw re-partitions the study — rows sealed since upload
        become trainable, and two runs stop being comparable.

        **The grain answer is a precondition, not a decoration.** Constitution
        §01 fixes the pre-seal order and §02 says the seal cannot be drawn
        correctly without the grain; refusing here is that ordering made
        executable, so a caller cannot seal first and ask afterwards.
        """
        if self.grain is None:
            raise ProjectError(
                "The test set cannot be sealed before the grain question is "
                "answered: whether one person can appear in more than one row "
                "decides how the held-out rows are chosen. Constitution §01 "
                "fixes that order, and §02 is why.")
        if self.barrier_raised:
            raise ProjectError(
                "This project already has a sealed test set. Redrawing it would "
                "re-partition the study: rows sealed since upload would become "
                "trainable and earlier results would no longer be comparable.")
        unknown = [l for l in labels if l not in self.df.index]
        if unknown:
            raise ProjectError(
                f"{len(unknown)} sealed label(s) are not in this table: {unknown[:5]}.")
        self.lockbox = {
            "labels": [_label(l) for l in labels],
            "n_total": int(len(self.df)),
            "n_test": int(len(labels)),
            "target_col": self.target or "",
            # The seal states its own basis, and where that basis came from
            # (constitution §03). Both are copied from the recorded grain answer
            # rather than re-derived, so the seal and the transcript cannot
            # disagree about what the user said.
            "seal_basis": self.grain["basis"],
            "basis_source": self.grain["basis_source"],
            "group_col": self.grain.get("group_col"),
            "n_groups": self.grain.get("n_groups"),
            **disclosure,
        }
        return self.record(
            kind="seal_lockbox", subject=self.target or "",
            text=(f"A test set of {len(labels)} rows was sealed before exploration "
                  f"and held by row label, on the basis '{self.grain['basis']}' "
                  f"({self.grain['basis_source']})."),
            payload={"n_test": int(len(labels)),
                     "seal_basis": self.grain["basis"],
                     "basis_source": self.grain["basis_source"]})

    def assert_identity_intact(self) -> None:
        """Every sealed label must still name a row. The post-barrier check."""
        if not self.barrier_raised:
            return
        missing = [l for l in self.lockbox["labels"] if l not in self.df.index]
        if missing:
            raise ProjectError(
                f"{len(missing)} sealed row label(s) are no longer in the table "
                f"(e.g. {missing[:5]}). Something renumbered the rows after the "
                "test set was sealed, so the quarantine no longer refers to the "
                "rows it was drawn from.")

    # ── the active cohort filter ────────────────────────────────────────────

    def set_cohort(self, column: str, value: Any, labels: Sequence[Any],
                   **detail: Any) -> Decision:
        """Restrict the analysis to one group, by row label.

        First-class rather than a filter applied somewhere and forgotten: every
        number computed while this is set is about a subset, and the record has
        to say which.
        """
        if column not in list(self.df.columns):
            raise ProjectError(f"No column named '{column}' to form a cohort on.")
        self.cohort = {
            "column": str(column), "value": value,
            "label": str(detail.pop("label", f"{column} = {value}")),
            "labels": [_label(l) for l in labels],
            "n_rows": int(len(labels)), "n_total": int(len(self.df)),
            "target_col": self.target or "", **detail,
        }
        self.findings_stale = True
        return self.record(
            kind="set_cohort", subject=str(column),
            text=(f"The analysis was restricted to {self.cohort['label']} — "
                  f"{len(labels)} of {len(self.df)} rows."),
            payload={"column": str(column), "n_rows": int(len(labels))})

    def clear_cohort(self) -> Decision:
        previous = self.cohort["label"] if self.cohort else None
        self.cohort = None
        self.findings_stale = True
        return self.record(kind="clear_cohort", subject="",
                           text=f"The cohort filter ({previous}) was removed; "
                                "the analysis is over the whole study again."
                                if previous else "No cohort filter was set.")

    @property
    def working_table(self) -> pd.DataFrame:
        """The rows the analysis is currently about.

        `get_data()` in the Streamlit app applies the active cohort filter with
        exactly two `full_study=True` escapes, enforced by nothing but a default
        parameter. Here the filter is a field, so "which rows is this number
        about?" has one answer and it is inspectable.
        """
        if self.cohort and self.cohort.get("labels"):
            return self.df.loc[[l for l in self.cohort["labels"] if l in self.df.index]]
        return self.df

    # ── invalidation ────────────────────────────────────────────────────────

    def invalidate(self, changed_stage: str = "data",
                   keep: Sequence[str] = ()) -> Dict[str, Any]:
        """Mark everything downstream of `changed_stage` stale.

        Delegates the *which* to `turbotab.cascade`, so this project and the
        Streamlit app answer from the same graph rather than from two lists that
        drift. Nothing is destroyed — findings are marked, which is what makes
        "the past is editable, never silently destroyed" true.
        """
        from turbotab import cascade
        keys = cascade.keys_to_clear(changed_stage, keep=keep)
        if any(k in keys for k in ("dataset_profile", "eda_results")):
            self.findings_stale = True
        if "preprocessing_pipelines_by_model" in keys:
            self.pipeline_specs = {}
        return {"stage": changed_stage, "keep": list(keep),
                "cleared": sorted(keys),
                "provenance_sections":
                    sorted(cascade.provenance_sections_to_clear(changed_stage, keep))}

    # ── readiness ───────────────────────────────────────────────────────────

    def readiness(self):
        """The Router's readiness function, over this project's state."""
        from turbotab import readiness as _readiness
        return _readiness.assess(self._readiness_state(), self.workflow_mode)

    def _readiness_state(self) -> Dict[str, Any]:
        """This project, in the shape the shared predicates read.

        Deliberately the *same* predicates the Streamlit sidebar uses. If the
        two doors computed readiness differently they would disagree about which
        step comes next, which is a fork in the interview rather than in the UI.
        """
        return {
            "working_data": self.df,
            "data_config": _TargetView(self.target),
            "feature_selection_results": None,
            "preprocessing_pipeline": self.pipeline_specs or None,
            "trained_models": {},
            "permutation_importance": {},
            "shap_results": {},
            "sensitivity_seed_results": None,
            "report_data": None,
            "hypothesis_test_results": None,
            "custom_table1_tests": [],
            "feature_engineering_applied": bool(self.applied_fixes),
        }

    def fingerprint(self) -> str:
        """A content hash of the working table: values, row labels, dtypes.

        Exists so "declining a preview left the project untouched" is a thing a
        test can assert rather than a thing a comment claims.
        """
        h = hashlib.sha256()
        h.update(self.df.to_csv(index=True).encode("utf-8"))
        h.update("|".join(f"{c}:{d}" for c, d in
                          zip(map(str, self.df.columns), map(str, self.df.dtypes))).encode("utf-8"))
        return h.hexdigest()

    def apply_fix(self, new_df: pd.DataFrame, finding_id: str, title: str,
                  description: str, row_identity_preserved: bool) -> Decision:
        """Install a repaired frame, keeping the one it replaced.

        The previous frame is pushed onto a stack rather than dropped, because
        `ARCHITECTURE.md` §02 requires fixes to be *reversible*, and a fix you
        cannot undo is a fix the user has to be certain about before they can
        see what it did — which is the blind consent the preview exists to
        avoid.

        `row_identity_preserved` is recorded on the decision rather than acted
        on. Four fix kinds renumber the index, and when that happens every row
        label stored earlier stops naming the same row. The skeleton has no
        lockbox to invalidate yet, so the honest thing is to write down that it
        happened; the step that seals a test set will need to read this.
        """
        self._history.append((finding_id, self.df))
        self.df = new_df
        self.findings_stale = True
        return self.record(
            kind="apply", subject=finding_id, text=description,
            payload={"title": title,
                     "row_identity_preserved": bool(row_identity_preserved),
                     "reverts_to": len(self._history) - 1},
        )

    def revert_last_fix(self) -> Decision:
        """Undo the most recent applied fix. Appends; never erases the record."""
        if not self._history:
            raise ProjectError("No applied fix to undo.")
        finding_id, previous = self._history.pop()
        self.df = previous
        self.findings_stale = True
        return self.record(
            kind="revert", subject=finding_id,
            text="That change was undone; the table is back as it was.",
            payload={"undid": finding_id},
        )

    @property
    def applied_fixes(self) -> List[str]:
        return [fid for fid, _ in self._history]

    def set_findings(self, findings: List[Dict[str, Any]],
                     profile: Optional[Dict[str, Any]] = None) -> None:
        """Install a freshly computed finding set. Clears the stale mark."""
        self.findings = list(findings)
        if profile is not None:
            self.profile = profile
        self.findings_stale = False

    def finding(self, finding_id: str) -> Dict[str, Any]:
        for f in self.findings:
            if f.get("id") == finding_id:
                return f
        raise ProjectError(f"No finding with id '{finding_id}' in this project.")

    # ── the wire ────────────────────────────────────────────────────────────

    def to_dict(self, include_rows: bool = False) -> Dict[str, Any]:
        """Serialize. The frame is a handle, not content — it never goes in.

        `row_labels` is included only on request: it is the row identity, and on
        a large table it is also the largest thing here.
        """
        out: Dict[str, Any] = {
            "id": self.id,
            "name": self.name,
            "created_at": self.created_at,
            "n_rows": int(len(self.df)),
            "n_columns": int(len(self.df.columns)),
            "row_identity": "index_labels",
            "target": self.target,
            "task_type": self.task_type,
            "task_confidence": self.task_confidence,
            "task_overridden": self.task_overridden,
            "task_reasons": list(self.task_reasons),
            "columns": self.columns,
            "decisions": [d.to_dict() for d in self.decisions],
            "findings": self.findings,
            "findings_stale": self.findings_stale,
            "applied_fixes": self.applied_fixes,
            "engineered": self.engineered,
            "deferred_transforms": self.deferred_transforms,
            "selection_spec": self.selection_spec,
            "features_settled": self.features_settled,
            "stale_downstream": self.stale_downstream,
            "grain": self.grain,
            "lockbox": self.lockbox,
            "barrier_raised": self.barrier_raised,
            "cohort": self.cohort,
            "n_working_rows": int(len(self.working_table)),
            "pipeline_specs": self.pipeline_specs,
            "workflow_mode": self.workflow_mode,
            "readiness": self.readiness().to_dict(),
            "fingerprint": self.fingerprint(),
            "profile": self.profile,
        }
        if include_rows:
            out["row_labels"] = self.row_labels
        return out

    def head(self, n: int = 8) -> Dict[str, Any]:
        """A small sample for the interface, carrying its row labels with it.

        The labels travel with the rows so the frontend never has to say "row 3"
        and mean the fourth position.
        """
        sample = self.df.head(n)
        return {
            "columns": [str(c) for c in sample.columns],
            "labels": [_label(v) for v in sample.index],
            "rows": [["" if pd.isna(v) else str(v) for v in row]
                     for row in sample.itertuples(index=False, name=None)],
        }


class ProjectStore:
    """In-memory project registry.

    Deliberately a dict. `ARCHITECTURE.md` §02 records a ``_NEVER_PERSIST``
    contract that is stronger than its documentation, and §04 flags persistence
    as unsolved rather than solved. A skeleton that quietly wrote projects to
    disk would resolve that open question by accident.
    """

    def __init__(self) -> None:
        self._projects: Dict[str, AnalysisProject] = {}

    def add(self, project: AnalysisProject) -> AnalysisProject:
        self._projects[project.id] = project
        return project

    def get(self, project_id: str) -> AnalysisProject:
        if project_id not in self._projects:
            raise ProjectError(f"No project '{project_id}'. Projects live in memory "
                               "only and do not survive a server restart.")
        return self._projects[project_id]

    def __len__(self) -> int:
        return len(self._projects)
