"""The specification curve (Simonsohn, Simmons & Nelson 2020), an engine method core (T3).

"Which of my decisions mattered?" (BLUEPRINT §11, after the lock): the estimate of the exposure
under every combination of the plan's recorded choices and the alternatives declared beside them,
sorted, with the choices each specification took marked beneath it. It is sensitivity and never a
way to choose: the primary (every choice as recorded) stays the reported estimate whatever the
others say (§11.4).

**Inputs, explicit.** Each :class:`Choice` is one fork the decision log knows: the option the plan
recorded (``primary``) and the alternatives declared for it, each an :class:`Alternative` that
changes the adjustment set (``add``, ``drop``), restricts the rows (``keep``: an exclusion rule) or
names another column for the exposure (``exposure``, on the same scale). Wiring the decision log's
records into choices belongs to routing (packages E1, D1, C1); this module only takes them.

**The lock.** Specification estimates are estimates (calm/FOUNDATION §5 rule 6; Gelman & Loken
2013's forks: "choices of control variables in a regression, transformations, and data coding and
excluding rules"). Before the plan is locked the curve is refused, and nothing is fitted: the
result carries the line saying when it opens (the view's ``sealed``) and no specification. Only a
real lock opens it: the lock's id, or the ``lock_plan`` record in force; None, an empty id, False or
anything else is no lock.

**Which specifications.** Every combination of the choices' options (the curve's own definition).
Above :data:`CAP` combinations a stated rule draws :data:`CAP` of them, reproducibly from
``seed``: (1) the primary; (2) every departure from it in one choice only, so every option is seen
against the primary; (3) the rest drawn at random, each choice's option drawn independently with
every option equally likely (so every combination is equally likely), a repeat drawn again. When
(1) and (2) alone exceed the cap the curve is refused: fewer alternatives, or a higher cap, are the
exits. ``crossing="one_at_a_time"`` asks for (1) and (2) only, the customary sensitivity table.

**Each specification is fitted as the primary is** (:mod:`turbotab.core.models.inference`): least
squares with HC3 intervals on t(n − p) for a numeric outcome, logistic regression with Wald
intervals for a yes/no one (Firth's fit, with profile intervals, where a column separates the
outcome), CR2 intervals with Bell–McCaffrey degrees of freedom when the rows repeat within a unit.
The estimate is the exposure's coefficient: a difference in the mean outcome per unit of the
exposure, or a difference in log-odds. A specification's rows are those its rule keeps with every
column it reads present; its n is said beside it.

**A survey design** (the surveyed-population answer) is honored: every specification is the
design-based fit of :func:`turbotab.core.models.survey.survey_table` (Taylor linearization, t on
PSUs − strata), and an exclusion rule is a *domain*, never a deletion: the rows it leaves keep their
stratum and PSU and contribute a score of zero. A specification whose design leaves no degrees of
freedom is listed as not estimated, with its reason.

**One scale.** Every specification must estimate one quantity on one scale (the view refuses a mix):
an alternative exposure must declare its scale, the primary exposure's scale must be declared beside
it, and the two must be the same; an undeclared scale is refused, never assumed to match. An
exposure the fit would split into several coefficients (a category) is refused. An option whose
``drop`` names the exposure is refused: the exposure is fitted in every specification, so it would
be the primary again under another name.

**No joint test.** Simonsohn et al. also propose a joint test across specifications against a null
generated by permutation or by a bootstrap under the null. Its procedure could not be checked here
against the paper's text or a reference implementation (the paper is closed; R's specr 1.0.0 has no
such function), so it is not computed: the curve is descriptive. The summary counts are counts: the
median estimate and how many intervals lie wholly above or below zero, never a p-value.

The goal that offers it: Estimate an effect. Predict refuses it (its choices are made inside the
folds and compared by their scores), and Describe, which fits no exposure model, does not offer it.
"""
from __future__ import annotations

import math
from dataclasses import asdict, dataclass, field
from itertools import product
from typing import Any, Callable, Mapping, Sequence

import numpy as np
import pandas as pd

CAP = 1000  # specifications fitted at most (a convention; the paper's examples have up to 1,728)
LEVEL = 0.95
GOALS: tuple[str, ...] = ("describe", "estimate", "predict")
CROSSINGS: tuple[str, ...] = ("all", "one_at_a_time")

SOURCES = {
    "ssn2020": "Simonsohn, Simmons & Nelson 2020, Nat Hum Behav 4:1208 (doi:10.1038/s41562-020-0912-z)",
    "gelman2013": "Gelman & Loken 2013, The garden of forking paths",
    "lumley": "Lumley 2010, Complex Surveys: A Guide to Analysis Using R (Wiley)",
}

LOCK_EXIT = {"label": "Press Fit to lock the plan; the curve opens after it", "stage": "fit"}
FEWER_EXIT = {"label": "Declare fewer alternatives"}
ONE_AT_A_TIME_EXIT = {"label": "Change one choice at a time instead", "crossing": "one_at_a_time"}
ESTIMATE_EXIT = {"label": "Ask it under Estimate an effect", "goal": "estimate"}
SCORES_EXIT = {"label": "Compare the models by their cross-validated scores", "stage": "models"}
PRIMARY_EXIT = {"label": "Revisit the recorded choice that leaves the primary without an estimate",
                "stage": "models"}
SCALE_EXIT = {"label": "Declare the scale of each column you study (the same for every one)"}


class SpecCurveRefused(ValueError):
    """The curve cannot be drawn as asked; the message says why, ``exits`` the ways forward."""

    def __init__(self, message: str, exits: Sequence[Mapping[str, Any]] = ()):
        super().__init__(message)
        self.exits = [dict(e) for e in exits]


# ── which goal offers it ─────────────────────────────────────────────────────


@dataclass(frozen=True)
class Eligibility:
    offered: bool
    says: str
    exits: tuple[dict[str, Any], ...] = ()


def eligible(goal: str) -> Eligibility:
    """Whether ``goal`` (describe · estimate · predict) offers the specification curve."""
    if goal not in GOALS:
        raise ValueError(f"goal {goal!r} is unknown")
    if goal == "predict":
        return Eligibility(False, "Under Predict the choices are made inside each training fold and "
                                  "compared by their scores, so there is no single estimate to "
                                  "follow across them.", (dict(SCORES_EXIT),))
    if goal == "describe":
        return Eligibility(False, "Describe fits no model of what you study, so there is no estimate "
                                  "to follow across the choices.", (dict(ESTIMATE_EXIT),))
    return Eligibility(True, "The estimate under every combination of your recorded choices and "
                             "the alternatives declared beside them, after the lock.")


# ── the forks ────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class Alternative:
    """One option of a choice. ``add``/``drop``: covariates it adds to or removes from the base
    adjustment set; ``keep``: the rows it keeps (a boolean per row, aligned with the frame, or a
    Series indexed as the frame), applied with every other choice's rule; ``exposure``: another
    column for the exposure, whose ``scale`` must be the primary exposure's."""

    key: str
    label: str
    add: tuple[str, ...] = ()
    drop: tuple[str, ...] = ()
    keep: Any = None
    exposure: str | None = None
    scale: str | None = None


@dataclass(frozen=True)
class Choice:
    """A fork: its options, the one the plan recorded (``primary``), and the decision that recorded
    it (a decision kind or record id, for the record)."""

    key: str
    label: str
    options: tuple[Alternative, ...]
    primary: str
    decision: str = ""

    def option(self, key: str) -> Alternative:
        for o in self.options:
            if o.key == key:
                return o
        raise KeyError(f"choice {self.key!r} has no option {key!r}")


# ── results ──────────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class SpecFit:
    """What one specification's fit returns."""

    estimate: float
    low: float | None
    high: float | None
    n: int
    se: float | None = None
    p: float | None = None
    df: float | None = None
    estimator: str = ""
    covariance: str = ""
    refused: str | None = None  # why it has no estimate, when it has none


@dataclass(frozen=True)
class Spec:
    key: str
    picks: dict[str, str]
    primary: bool
    estimate: float
    low: float | None
    high: float | None
    n: int
    se: float | None = None
    p: float | None = None
    df: float | None = None
    estimator: str = ""
    covariance: str = ""
    scale_key: str = ""


@dataclass(frozen=True)
class NotEstimated:
    key: str
    picks: dict[str, str]
    primary: bool
    reason: str


@dataclass(frozen=True)
class Summary:
    """Counts over the estimated specifications: descriptive, never a test."""

    k: int
    median: float
    lowest: float
    highest: float
    above: int  # intervals wholly above zero
    below: int  # wholly below zero
    spanning: int  # including zero, or no interval
    primary_rank: int | None  # the primary's place among the sorted estimates, 1 = lowest


@dataclass
class SpecCurve:
    estimate_label: str
    choices: list[dict[str, Any]]
    specs: list[Spec] = field(default_factory=list)
    not_estimated: list[NotEstimated] = field(default_factory=list)
    total: int = 0  # every combination of the options
    drawn: int = 0  # the specifications fitted
    sampled: bool = False
    rule: str | None = None  # the sampling rule, when the cap applied
    crossing: str = "all"
    summary: Summary | None = None
    level: float | None = LEVEL
    sealed: str | None = None  # before the lock: when it opens; nothing is fitted
    plan_lock: str | None = None
    weighted: bool = False
    clustered: bool = False
    exits: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def to_view(self) -> dict[str, Any]:
        """The view's data contract (``frontend/src/components/views/specCurve.ts``,
        ``SpecCurveData``): nothing estimated while ``sealed``."""
        return {
            "estimateLabel": self.estimate_label,
            "choices": [{"key": c["key"], "label": c["label"],
                         "options": [{"key": o["key"], "label": o["label"]} for o in c["options"]]}
                        for c in self.choices],
            "specs": [] if self.sealed else [
                {"key": s.key, "estimate": s.estimate, "low": s.low, "high": s.high, "n": s.n,
                 "primary": s.primary, "picks": dict(s.picks), "scaleKey": s.scale_key}
                for s in self.specs],
            "zero": True,
            "level": None if self.sealed else self.level,
            "sealed": self.sealed,
        }

    @property
    def says(self) -> str:
        return _says(self)


# ── enumeration ──────────────────────────────────────────────────────────────


def _key(picks: Mapping[str, str], order: Sequence[str]) -> str:
    return "|".join(f"{c}={picks[c]}" for c in order)


def count(choices: Sequence[Choice]) -> int:
    """Every combination of the choices' options."""
    return math.prod(len(c.options) for c in choices)


def enumerate_specs(choices: Sequence[Choice], *, cap: int = CAP, seed: int = 0,
                    crossing: str = "all") -> tuple[list[dict[str, str]], int, str | None]:
    """The specifications to fit, the primary first: (picks of each, the total, the sampling rule
    when the cap applied, else None). The module docstring states the rule."""
    if crossing not in CROSSINGS:
        raise ValueError(f"crossing {crossing!r} is not one of {CROSSINGS}")
    order = [c.key for c in choices]
    primary = {c.key: c.primary for c in choices}
    total = count(choices)
    departures = [{**primary, c.key: o.key} for c in choices for o in c.options if o.key != c.primary]
    if crossing == "one_at_a_time":
        if 1 + len(departures) > cap:
            raise SpecCurveRefused(
                f"Changing one choice at a time gives {1 + len(departures):,} specifications, more "
                f"than the {cap:,} fitted at most.", (FEWER_EXIT,))
        return [primary, *departures], total, None
    if total <= cap:
        options = [[o.key for o in c.options] for c in choices]
        rest = [dict(zip(order, combo)) for combo in product(*options)]
        return [primary, *[p for p in rest if p != primary]], total, None
    if 1 + len(departures) > cap:
        raise SpecCurveRefused(
            f"The choices declare {total:,} combinations; even the primary and each one-choice "
            f"departure from it ({1 + len(departures):,}) exceed the {cap:,} fitted at most.",
            (FEWER_EXIT,))
    chosen = [primary, *departures]
    seen = {_key(p, order) for p in chosen}
    rng = np.random.default_rng(seed)
    while len(chosen) < cap:
        draw = {c.key: c.options[int(rng.integers(0, len(c.options)))].key for c in choices}
        k = _key(draw, order)
        if k in seen:
            continue
        seen.add(k)
        chosen.append(draw)
    rule = (f"{total:,} combinations exceed the {cap:,} fitted, so the curve holds the primary, "
            f"its {len(departures):,} one-choice departures, and {cap - 1 - len(departures):,} "
            f"combinations drawn at random (every combination equally likely; seed {seed}).")
    return chosen, total, rule


# ── the curve ────────────────────────────────────────────────────────────────


SEALED = ("The specification curve opens after Fit locks the plan: shown before, it would invite "
          "choosing the plan by its estimate.")


def _check(choices: Sequence[Choice]) -> None:
    if not choices:
        raise SpecCurveRefused("No choice has a declared alternative, so there is nothing to vary: "
                               "the curve would be the primary alone.",
                               ({"label": "Declare an alternative for a choice"},))
    keys = [c.key for c in choices]
    if len(set(keys)) != len(keys):
        raise ValueError("two choices share a key")
    for c in choices:
        if len(c.options) < 2:
            raise SpecCurveRefused(f"“{c.label}” has no declared alternative to the recorded "
                                   f"option.", ({"label": "Declare an alternative for it"},))
        okeys = [o.key for o in c.options]
        if len(set(okeys)) != len(okeys) or c.primary not in okeys:
            raise ValueError(f"choice {c.key!r}: option keys repeat or the primary is not among them")


def is_lock(lock: Any) -> bool:
    """Whether ``lock`` is a real plan lock: a non-empty lock id, or the ``lock_plan`` record in
    force (:func:`turbotab.core.plan_lock.current_lock`). None, an empty id, False, or any other
    placeholder is no lock, so the curve stays sealed."""
    if isinstance(lock, str):
        return bool(lock.strip())
    decision = getattr(lock, "decision", None)
    return (decision is not None and getattr(decision, "kind", None) == "lock_plan"
            and bool(getattr(lock, "id", None)))


def specification_curve(choices: Sequence[Choice], fit: Callable[[Mapping[str, str]], SpecFit], *,
                        lock: Any, estimate_label: str, goal: str = "estimate",
                        scale_key: str = "", cap: int = CAP, seed: int = 0,
                        crossing: str = "all", weighted: bool = False,
                        clustered: bool = False) -> SpecCurve:
    """The curve: each specification ``fit(picks)`` returns, after the lock only.

    ``lock`` is the plan lock in force (:func:`turbotab.core.plan_lock.current_lock`) or its id;
    anything else (None, "", False) leaves the result sealed and ``fit`` is never called. :func:`linear_fitter` makes ``fit`` for
    the linear family. Raises :class:`SpecCurveRefused` with its exits."""
    e = eligible(goal)
    if not e.offered:
        raise SpecCurveRefused(e.says, e.exits)
    _check(choices)
    described = [{"key": c.key, "label": c.label, "primary": c.primary, "decision": c.decision,
                  "options": [{"key": o.key, "label": o.label} for o in c.options]}
                 for c in choices]
    if not is_lock(lock):
        return SpecCurve(estimate_label=estimate_label, choices=described, total=count(choices),
                         sealed=SEALED, crossing=crossing, level=None,
                         exits=[dict(LOCK_EXIT)], weighted=weighted, clustered=clustered)
    picks_list, total, rule = enumerate_specs(choices, cap=cap, seed=seed, crossing=crossing)
    order = [c.key for c in choices]
    specs: list[Spec] = []
    missing: list[NotEstimated] = []
    for i, picks in enumerate(picks_list):
        k = _key(picks, order)
        try:
            got = fit(picks)
        except SpecCurveRefused as refusal:
            if i == 0:
                raise
            missing.append(NotEstimated(k, dict(picks), False, str(refusal)))
            continue
        if got.refused is not None or not math.isfinite(got.estimate):
            if i == 0:
                raise SpecCurveRefused(
                    f"The primary specification has no estimate here: "
                    f"{got.refused or 'the fit returned none'}", (PRIMARY_EXIT, FEWER_EXIT))
            missing.append(NotEstimated(k, dict(picks), False, got.refused or "no estimate"))
            continue
        specs.append(Spec(k, dict(picks), i == 0, float(got.estimate), got.low, got.high,
                          int(got.n), got.se, got.p, got.df, got.estimator, got.covariance,
                          scale_key))
    return SpecCurve(estimate_label=estimate_label, choices=described, specs=specs,
                     not_estimated=missing, total=total, drawn=len(picks_list),
                     sampled=rule is not None, rule=rule, crossing=crossing,
                     summary=summarize(specs), level=LEVEL,
                     plan_lock=lock if isinstance(lock, str) else str(lock.id),
                     weighted=weighted, clustered=clustered)


def summarize(specs: Sequence[Spec]) -> Summary | None:
    """Counts over the estimated specifications (descriptive)."""
    if not specs:
        return None
    est = np.array([s.estimate for s in specs], dtype=float)
    above = sum(1 for s in specs if s.low is not None and s.low > 0)
    below = sum(1 for s in specs if s.high is not None and s.high < 0)
    ordered = sorted(specs, key=lambda s: (s.estimate, s.key))
    rank = next((i + 1 for i, s in enumerate(ordered) if s.primary), None)
    return Summary(k=len(specs), median=float(np.median(est)), lowest=float(est.min()),
                   highest=float(est.max()), above=above, below=below,
                   spanning=len(specs) - above - below, primary_rank=rank)


# ── the linear family's fit of one specification ─────────────────────────────


def _mask(keep: Any, index: pd.Index) -> np.ndarray:
    if isinstance(keep, pd.Series):
        if not keep.index.equals(index):
            if keep.index.has_duplicates or not index.isin(keep.index).all():
                raise ValueError("an exclusion rule is labeled by rows the frame does not hold")
            keep = keep.reindex(index)
        return keep.fillna(False).to_numpy(dtype=bool)
    out = np.asarray(keep, dtype=bool)
    if out.shape != (len(index),):
        raise ValueError("an exclusion rule must mark every row of the frame")
    return out


def linear_fitter(frame: pd.DataFrame, *, outcome: str, exposure: str,
                  covariates: Sequence[str], choices: Sequence[Choice], task: str,
                  classes: Sequence[Any] | None = None, units: Any = None,
                  unit_name: str | None = None, design: Any = None,
                  exposure_scale: str = "") -> Callable[[Mapping[str, str]], SpecFit]:
    """``fit(picks)`` for the linear family: the exposure's coefficient with the primary's own
    interval (module docstring). ``frame`` holds the analysis rows indexed by row id (under a survey
    design, the ids in ``design``); ``units`` names each row's unit when rows repeat (CR2);
    ``design`` (:class:`~turbotab.core.models.survey.SurveyDesign`) makes every fit design-based."""
    from turbotab.core.models import inference as I
    from turbotab.core.models import survey as S

    if task not in ("regression", "binary"):
        raise SpecCurveRefused(
            "The curve follows one coefficient per specification; for this outcome the model "
            "gives " + ("one per category (a multiclass outcome)" if task == "multiclass" else
                        "a coefficient on another scale (" + task.replace("_", " ") + ")")
            + ", which this curve does not yet follow.", ({"label": "Use a numeric or yes/no "
                                                                    "outcome"},))
    by_choice = {c.key: c for c in choices}
    for c in choices:
        for o in c.options:
            if o.exposure is not None and o.exposure != exposure:
                if not (o.scale or "").strip() or not exposure_scale.strip():
                    raise SpecCurveRefused(
                        f"“{o.label}” swaps what you study for `{o.exposure}`, but the scale of "
                        + ("both" if not (o.scale or "").strip() and not exposure_scale.strip() else
                           f"`{o.exposure}`" if not (o.scale or "").strip() else f"`{exposure}`")
                        + " is not declared, so the curve cannot tell whether every estimate is "
                        "the same quantity.",
                        (SCALE_EXIT, {"label": "Draw it as a curve of its own"}))
                if o.scale != exposure_scale:
                    raise SpecCurveRefused(
                        f"“{o.label}” measures what you study on another scale "
                        f"({o.scale} against {exposure_scale}), so its estimate is not the same "
                        "quantity and the curve would mix scales.",
                        ({"label": "Draw it as a curve of its own"},))
            dropped = sorted({exposure, o.exposure or exposure}.intersection(o.drop))
            if dropped:
                raise SpecCurveRefused(
                    f"“{o.label}” drops {', '.join(f'`{d}`' for d in dropped)}, the column every "
                    "specification studies, so it would stay in and this would be the "
                    "primary again under another name.",
                    ({"label": "Remove what you study from what it drops"},
                     {"label": "Declare another column to study as an alternative instead"}))
    unit = None if units is None else np.asarray(pd.Series(units).to_numpy(), dtype=object)
    if unit is not None and len(unit) != len(frame):
        raise ValueError("units must name every row's unit")

    def fit(picks: Mapping[str, str]) -> SpecFit:
        cols = list(dict.fromkeys(covariates))
        x = exposure
        keep = np.ones(len(frame), dtype=bool)
        for ck, ok in picks.items():
            o = by_choice[ck].option(ok)
            cols = [c for c in cols if c not in o.drop] + [c for c in o.add if c not in cols]
            if o.exposure is not None:
                x = o.exposure
            if o.keep is not None:
                keep &= _mask(o.keep, frame.index)
        cols = [c for c in cols if c != x]
        used = frame.loc[:, [outcome, x, *cols]]
        keep &= used.notna().all(axis=1).to_numpy()
        rows = used.loc[keep]
        if not pd.api.types.is_numeric_dtype(rows[x]):
            raise SpecCurveRefused(
                f"`{x}` is a category, so the fit would give one coefficient per level; the curve "
                "follows one number per specification.",
                ({"label": f"Code `{x}` as one contrast (0 and 1)"},))
        X = pd.get_dummies(rows[[x, *cols]], drop_first=True, dtype=float).astype(float)
        X = X[[x, *[c for c in X.columns if c != x]]]
        y = rows[outcome].to_numpy()
        # Under a design the n is the domain's: the rows placed in it with a positive weight, the
        # rows survey_table fits (a row of zero or missing weight is outside the domain).
        n = int(len(rows)) if design is None else S.domain_of(X.index, design).n
        if n <= X.shape[1] + 1:
            return SpecFit(math.nan, None, None, n, refused=f"only {n} rows with every column "
                                                             f"present, too few to fit")
        if design is not None:
            table = S.survey_table(task, X, y, classes, design)
        else:
            clusters = I.INDEPENDENT
            if unit is not None:
                u = unit[keep]
                codes, uniq = pd.factorize(pd.Series(u), sort=True)
                if len(uniq) < n:
                    clusters = I.Clusters(column=unit_name or "unit", codes=codes.astype(np.int64),
                                          n_clusters=int(len(uniq)))
            table = I.inference_table(task, X, y, classes, clusters)
        row = next(r for r in table.rows if r["feature"] == x)
        refused = table.info.get("refused")
        if refused or row["ci_low"] is None:
            return SpecFit(math.nan if row["estimate"] is None else row["estimate"], None, None, n,
                           estimator=table.info.get("estimator", ""),
                           refused=refused or "no interval could be computed")
        return SpecFit(float(row["estimate"]), row["ci_low"], row["ci_high"], n, se=row["se"],
                       p=row["p"], df=row["df"], estimator=table.info.get("estimator", ""),
                       covariance=table.info.get("covariance", ""))

    return fit


def lock_of(records: Sequence[Any]) -> Any:
    """The plan lock in force in a decision log (None before Fit)."""
    from turbotab.core.plan_lock import current_lock

    return current_lock(records)


# ── words ────────────────────────────────────────────────────────────────────


def _num(x: float) -> str:
    return f"{x:.3g}".replace("-", "−")


def _says(r: SpecCurve) -> str:
    if r.sealed:
        return r.sealed
    s = r.summary
    if s is None:
        return "No specification could be estimated."
    primary = next((x for x in r.specs if x.primary), None)
    text = (f"Across {s.k:,} specifications the estimate ranged from {_num(s.lowest)} to "
            f"{_num(s.highest)} (median {_num(s.median)})")
    if primary is not None:
        text += f"; the primary, {_num(primary.estimate)}, is the reported estimate"
    text += (f". {s.above:,} interval{'s' if s.above != 1 else ''} lay wholly above zero and "
             f"{s.below:,} wholly below.")
    if r.not_estimated:
        text += f" {len(r.not_estimated):,} could not be estimated, each with its reason."
    return text


def spec_curve_sentence(result: SpecCurve | None = None) -> str:
    """The methods sentence of the specification curve."""
    r = result
    sentence = ("As a sensitivity analysis after the analysis plan was locked, the exposure's "
                "estimate was refitted under every combination of the recorded analytic choices "
                "and the alternatives declared for them (a specification curve; Simonsohn, "
                "Simmons & Nelson 2020)")
    if r is not None and r.crossing == "one_at_a_time":
        sentence = ("As a sensitivity analysis after the analysis plan was locked, the exposure's "
                    "estimate was refitted with each recorded analytic choice changed, one at a "
                    "time, to each alternative declared for it")
    if r is not None and r.sampled:
        sentence += (f"; of the {r.total:,} combinations, the primary, every one-choice departure "
                     f"from it and a random draw of the rest were fitted ({r.drawn:,} in all)")
    sentence += ("; each was fitted as the primary analysis was, and the primary remains the "
                 "reported estimate.")
    if r is not None and r.weighted:
        sentence += (" Every specification was design-based, an exclusion rule defining a domain "
                     "of the full design.")
    sentence += " No joint test across specifications was computed."
    return sentence


# ── the contract ─────────────────────────────────────────────────────────────


def _register_contract() -> None:
    from turbotab.core.contracts import (CONTRACTS, ContractOption, MethodContract, Relation,
                                        register_contract)

    if "specification_curve" in CONTRACTS:
        return
    here = "turbotab.core.methods.spec_curve"
    inference = ("inference",)
    not_predict = ("Not offered under Predict: the choices are made inside each training fold and "
                   "compared by their scores")

    register_contract(MethodContract(
        key="specification_curve", label="Which of my decisions mattered? (specification curve)",
        slot="evaluation", scope="model", package="SPECCURVE", run_order=9.0,
        scope_note=("Refits the outcome model, on the analyzed rows, once per specification, as the "
                    "primary estimate is fitted under Estimate (BLUEPRINT §12 ruling 3), only after "
                    "the plan is locked. It reports; nothing it fits replaces the primary or "
                    "informs a choice."),
        needs=("the plan lock (after Fit)",
               "the recorded choices, each with at least one declared alternative",
               "a numeric or yes/no outcome and one exposure coefficient",
               "optional: the unit when rows repeat, the survey design"),
        question="Which of my decisions mattered?",
        options=(
            ContractOption(
                "all", "Every combination of the choices (the specification curve)",
                "Simonsohn, Simmons & Nelson 2020; R's specr",
                {"inference": "Sound as sensitivity after the lock: every declared fork crossed; "
                              "above 1,000 combinations a stated rule draws them",
                 "prediction": not_predict},
                {"inference": "recommended", "prediction": "not_offered"},
                {"inference": 0, "prediction": 0}),
            ContractOption(
                "one_at_a_time", "Each choice changed alone (a sensitivity table)",
                "The customary sensitivity analyses, one departure at a time",
                {"inference": "Sound, but misses choices that matter only together",
                 "prediction": not_predict},
                {"inference": "available", "prediction": "not_offered"},
                {"inference": 1, "prediction": 1}),
        ),
        storyboard=("take the plan as locked and each declared alternative",
                    "list every combination of the choices", "refit the estimate under each",
                    "sort them, the primary marked", "mark beneath each the option each choice took"),
        relations=(
            Relation("conflicts", "before_the_lock",
                     "refused before the plan is locked: nothing is fitted, and the curve says when "
                     "it opens", purposes=inference, rung="refused",
                     exits=("press Fit to lock the plan",), condition="no plan lock in force",
                     enforced_by=f"{here}:specification_curve", id="after_the_lock"),
            Relation("implies", "primary_stays_reported",
                     "the primary (every choice as recorded) stays the reported estimate; the "
                     "curve is sensitivity, never a way to choose", purposes=inference,
                     condition="always", enforced_by=f"{here}:specification_curve",
                     id="primary_reported"),
            Relation("implies", "sampled_beyond_cap",
                     "above 1,000 combinations the curve holds the primary, every one-choice "
                     "departure and a seeded random draw of the rest, and says so", when=("all",),
                     purposes=inference, condition="more than 1,000 combinations",
                     enforced_by=f"{here}:enumerate_specs", id="sampling_rule"),
            Relation("conflicts", "too_many_departures",
                     "refused when the primary and its one-choice departures alone exceed the cap",
                     purposes=inference, rung="refused", exits=("declare fewer alternatives",),
                     condition="1 + the alternatives declared > 1,000",
                     enforced_by=f"{here}:enumerate_specs", id="departures_exceed_cap"),
            Relation("conflicts", "one_scale",
                     "an alternative exposure on another scale, or one the fit splits by category, "
                     "is refused: every specification estimates one quantity",
                     purposes=inference, rung="refused", exits=("draw it as a curve of its own",),
                     condition="an exposure alternative whose scale differs",
                     enforced_by=f"{here}:linear_fitter", id="mixed_scales"),
            Relation("implies", "survey_population",
                     "under the surveyed-population answer every specification is design-based, "
                     "and an exclusion rule is a domain of the full design", purposes=inference,
                     condition="a survey design answered as the surveyed population",
                     enforced_by=f"{here}:linear_fitter", id="design_based_specs"),
            Relation("implies", "clustered_specs",
                     "each specification's interval is CR2 by the unit, as the primary's",
                     purposes=inference, condition="rows repeat within a unit",
                     enforced_by=f"{here}:linear_fitter", id="clustered_specs"),
            Relation("implies", "no_joint_test",
                     "the curve is descriptive: no joint test across specifications is computed",
                     purposes=inference, condition="always", enforced_by=f"{here}:summarize",
                     id="descriptive_only"),
            Relation("conflicts", "nothing_declared",
                     "refused when no choice has a declared alternative", purposes=inference,
                     rung="refused", exits=("declare an alternative for a choice",),
                     condition="no declared alternative", enforced_by=f"{here}:specification_curve",
                     id="no_alternatives"),
            Relation("conflicts", "not_under_prediction",
                     "not offered under Predict", purposes=("prediction",), rung="refused",
                     exits=("compare the models by their cross-validated scores",),
                     condition="the Predict goal", enforced_by=f"{here}:eligible",
                     id="predict_refused"),
        ),
        sources=tuple(SOURCES.values()),
        sentence=f"{here}:spec_curve_sentence"))


_register_contract()

__all__ = ["Alternative", "CAP", "Choice", "Eligibility", "NotEstimated", "SEALED", "Spec",
           "SpecCurve", "SpecCurveRefused", "SpecFit", "Summary", "count", "eligible",
           "enumerate_specs", "linear_fitter", "lock_of", "spec_curve_sentence",
           "specification_curve", "summarize"]
